- src/canvas.js
The `intersect` calculation only worked if the canvas was at 0,0 in the viewport. This should adjust it so that it takes into account the canvas position and size.
> Support offset canvas

- src/canvas.js
If the ref is only bound later the ResizeObserver won't be set up.
> Fix late ref for useMeasure

- src/hooks.js
Thanks for this library!
I was playing around with some type definitions for #11, and noticed this argument wasn't used.
> useThree: Remove unused argument placeholder

- .eslintrc.json
- .size-snapshot.json
- package.json
- yarn.lock
Hey there, I noticed this repo doesn't have even basic linting set up, despite its popularity. This PR adds eslint and a corresponding script in `package.json` to run it over `src/`.
Note that this PR doesn't attempt to address any of the current lint issues eslint has found. By the same token, I also haven't wired eslint up to `lint-staged` (and thus `husky`), so linting will not currently be enforced and needs to be invoked manually. I thought that might make review and adoption easier, so nothing blocks this PR and lints can be addressed gradually. (I'm also happy to help address them in a followup PR.)
Notably, I've included [`eslint-plugin-react-hooks`](https://www.npmjs.com/package/eslint-plugin-react-hooks), developed by the React team themselves, which is warning about quite a few …
> add eslint

- src/canvas.tsx
Currently main render loop is being run inside `useEffect`, which causes a noticeable 1 frame lag when compared to other animations, like cursor movement.
Switching to `useLayoutEffect` eliminates said lag.
> `useLayoutEffect` in render loop

- types/index.d.ts
This is the same change as #91 but was reverted in v2.1.6
> Fix typings

- index.ts
- rollup.config.js
- tsconfig.json
- types/index.d.ts
- types/src/canvas.d.ts
- types/src/hooks.d.ts
- types/src/reconciler.d.ts
A followup to #104, I converted index.ts into a TypeScript file as the generated typings lacked an entry point, and also changed the export mode for the typings to use a directory instead of a single file (necessary for the type definitions to be properly defined).
> Change the generation of the typings

- src/canvas.tsx
Right now, there's no easy way to stop propagation of events "handled" by 3d objects. This should fix that issue.
> properly `event.stopPropagation()` to allow outer DOM to pick up that signal

- src/canvas.tsx
Stopping "3D" propagation doesn't have to mean that you want to stop "source event" propagation. Exposing source event gives you fine-grain control over what you really want to do.
> Revert #135, expose `sourceEvent` instead

- src/canvas.tsx
Fix for #134 
The render runs with `useLayoutEffect`, that is being triggered before setting `size` and the `sharedState`, now they are synced
> useLayoutEffect when setting state

- index.ts
- src/three-types.ts
- types/index.d.ts
- types/src/three-types.d.ts
We have problems with the types of `args` property. These did not match the THREE class types and caused type script errors.
> Typescript refactoring / constructor parameters

- src/three-types.ts
I decided to group them all into a category, but I'm curious whether it would be better to group things by shape.
> Add shape-specific buffer geometries to tsx types

- package.json
- src/three-types.ts
- yarn.lock
Adds a `primitive` type. I'm not sure if we can add better typing for this but this should resolve https://github.com/drcmda/react-three-fiber/issues/160.
Also updated `three` dev dep to match peer dep (let me know if that should be separate PR).
> Add "primitive" type

- .size-snapshot.json
- package.json
- yarn.lock
Turns out `optionalDependencies` are installed automatically on `yarn install` but will be allowed to fail compared to `dependencies` (http://npm.github.io/using-pkgs-docs/package-json/types/optionaldependencies.html). Very confusing.
I decided it's best to add expo-three and expo-gl to devDependencies (to get the types), and have react-native as non-dependency (as it's required to actually get this target through package `"react-native"` entry point anyway), and the types are coming from `@types/react-native`.
> fix: move native dependencies

- src/canvas.tsx
Found a very important bug where the `gl` variable seem to be lost on dispose, but is somehow available from the state.
I was creating react native examples app and when navigating back and forth between examples, I noticed that the roots kept filling up, decreasing performance.
> fix: get gl from state

- src/canvas.tsx
@drcmda the mouse events are no longer forwarded to the handlers.
fix: https://github.com/react-spring/react-three-fiber/pull/200/commits/095898c0697a99f179a1b8b014a809ce795b35c3
> Eventobject handlers

- src/canvas.tsx
- src/targets/native/canvas.tsx
- src/targets/web/canvas.tsx
This an alternative approach to calculating the client bounds in relation to ray casting. It is made in effort to solve for additional use-cases referenced in https://github.com/react-spring/react-three-fiber/issues/219
The solution is to have a scroll event listener that sets a flag if the scroll event contains the canvas. Note that no reflow calculations happen inside the scroll listener. Then, mouse/pointer events will check if the flag has been set. If so, one recalculation is made.
I've setup some various test cases that can be seen here:
https://codesandbox.io/embed/react-three-fiber-scroll-bug-d7pmp
> Fix calculation of mouse event inside raycaster v2

- src/reconciler.tsx
There are helpers in three JS which inherited from Object3D, but they take different data (not only geometry and material) as constructor arguments (like [GridHelper](https://threejs.org/docs/index.html#api/en/helpers/GridHelper) ). So `args` should be checked for Object3D type also.
> Check args for Object3D.

- examples/webpack.config.js
I've got an error, that `react-use-measure` could not be found when I was trying to start the examples.
It works again when I comment out the alias for `react-use-measure` in the webpack config.
> Fix examples

- .eslintrc.json
- src/hooks.ts
Examples and a constructor call in useLoader body suggest that useLoader accepts a Loader class, not an instance.
```jsx
// one of the examples
useLoader(GLTFLoader, url, loader => {
const dracoLoader = new DRACOLoader()
dracoLoader.setDecoderPath('/draco-gltf/')
loader.setDRACOLoader(dracoLoader)
})
```
Initially, I wanted to go with `new () => THREE.Loader`, but THREE.Loader doesn't have a `load` method (lol).
DRACOLoader, GLTFLoader and TextureLoader have similar load methods, so I have added a generic type that fits all of them and may provide some inference 👇
---
TLDR:
> Fix type of useLoader first param

- src/targets/web/canvas.tsx
I noticed that the check for `window.ResizeObserver` was broken – the polyfill was never used if there was any `window` at all.
I don't think anyone would ever notice unless they were using a browser that doesn't have ResizeObserver yet (such as Safari)
> fix ResizeObserver polyfill check

- src/hooks.ts
Some loaders can return data that isn't of type `object` (for example `THREE.FileLoader`). This change only assigns `__$` to `data` when `data` has a `scene` property.
Relevant issue: https://github.com/react-spring/react-three-fiber/issues/254
> Fix useLoader for non-object data

- src/targets/web/canvas.tsx
It's not possible to consume this package without a loader that also transpiles modules in the node_modules folder, since `@juggle/resize-observer` at version 2.x doesn't export UMD or CJS builds, only ESM modules.
In the soon to be released v3 of `@juggle/resize-observer`, it will only export named exports, and will provide a UMD build by default as well as an ESM version.
Currently it supports both so this should be a non-breaking change.
> Updated @juggle/resize-observer import to match the next major version

- src/canvas.tsx
- src/targets/native/canvas.tsx
- src/targets/web/canvas.tsx
Closes #242
I've spread div props in web Canvas to match what's happening at runtime.
Interfaces support [declaration merging](https://www.typescriptlang.org/docs/handbook/declaration-merging.html#module-augmentation) so end-users can stick some more props onto them.
> Fix Canvas props

- .eslintrc.json
- package.json
- src/canvas.tsx
- src/declarations.d.ts
- src/targets/css2d.tsx
- src/targets/css3d.tsx
- src/targets/native/canvas.tsx
- src/targets/shared/web/ResizeContainer.tsx
- src/targets/svg.tsx
- src/targets/web.tsx
- tsconfig.json
Fixes https://github.com/react-spring/react-three-fiber/issues/242 on v4.
- Fix package.json typecheck script
Previously, it printed `error TS6053: File 'src/*.ts' not found.`
- Disable "@typescript-eslint/no-empty-interface"
I'd like to use interfaces instead of intersections (&) to get shorter error messages and make interface merging in user code possible. The rule has a configuration option that would probably make it okay, but I figured disabling it is just as good.
- Add declarations.d.ts to tell TS we don't have types for react-merge-refs.
> Add ResizeContainer props

- src/hooks.ts
about https://github.com/react-spring/react-three-fiber/issues/261
I've change the argument by judging whether the result of useLoader is an array
> Fix useLoader result types when multiple files loading

- package.json
- rollup.config.js
> Importing a specific renderer directly such as "react-three-fiber/svg" or "react-three-fiber/web" gives an error that no declaration files could be found.
_mentioned in https://github.com/react-spring/react-three-fiber/issues/268_
Write missing .d.ts files for targets with a rollup plugin.
As I mentioned in a DM, I had an idea to use rollup to emit the types.
Tried `rollup-plugin-ts`.
Emitted `dist` looked pretty well
But the build time grew by a factor of 10 😞 
```
./src/targets/web → dist/web.js...
Computed sizes of "dist\\web.js" with "esm" format
bundler parsing size: 34,072 B
browser parsing size (minified with terser): 19,513 B
download size (minified and gzipped): 7,048 B
treeshaked with rollup with production NODE_ENV and minified: 14,985 B  
import statements size of it: 856 B …
```
> Emit web.d.ts, svg.d.ts and native.d.ts

- src/targets/shared/web/Dom.tsx
Emits this to `/targets/shared/web/Dom.d.ts`
```tsx
import { Group } from 'three';
import React from 'react';
import { Assign } from 'utility-types';
import { ReactThreeFiber } from '../../../three-types';
export interface DomProps extends Omit<Assign<React.HTMLAttributes<HTMLDivElement>, ReactThreeFiber.Object3DNode<Group, typeof Group>>, 'ref'> {
children: React.ReactElement;
prepend?: boolean;
center?: boolean;
eps?: number;
}
export declare const Dom: React.ForwardRefExoticComponent<DomProps & React.RefAttributes<HTMLDivElement>>;
```
instead of [this](https://unpkg.com/react-three-fiber@4.0.6/targets/shared/web/Dom.d.ts).
Type intersection operator (`&`) is a bit underpowered for library authoring and `interface` give us both shorter error messages and prop conflict detection between …
> Use interface to intersect types for DomProps

- src/targets/native/canvas.tsx
On a React Native project running on Android, none of the pointer events are fired. This is due to a React Native specific optimization, http://facebook.github.io/react-native/docs/view.html#collapsable.
This is easily fixed by adding collapsable={false} to wrapping View component in the native canvas target.
> added collapsable={false} to native canvas target.

- src/canvas.tsx
avoids the warning “THREE.WebGLRenderer: .vr has been renamed to .xr”
see: https://github.com/mrdoob/three.js/blob/01579c3/src/Three.Legacy.js#L1742
> check for gl.xr before gl.vr

- src/canvas.tsx
Per conversation in Spectrum [here](https://spectrum.chat/react-three-fiber/general/how-to-set-premultipliedalpha~d1b0231e-6fdf-47f4-b9e1-776a264e32b6). Seems pretty straightforward. Sorry again for the delay. Please let me know if I missed something! 🙏
> Update type of props.gl passed into WebGLRenderer

- examples/package.json
- examples/yarn.lock
I noticed that building examples failed with an error about this dependency missing, so I added it. 
I'm unfamiliar with how the dependency is used, so it's unclear if there was another/better thing to do than just adding the dependency.
> add missing react-merge-refs dependency

- src/reconciler.tsx
Closes issue #321
I'm not sure if this is the preferred fix, but this will throw if a Suspense component 'finishes loading' with text in the tree. It makes it easier to diagnose these kinds of typos:
Note the space before the `{props.children}`
> Throw if text found in tree in Suspense boundary

- readme.md
Was trying to wrap my head around useResource and when I dug into the code, knowing it was a (helpful) wrapper around useRef helped. Maybe this amendment is useful?
Additionally, fixed paranthesis on the example, which I understand isn't fullsome. If you have ambitions for the docs here, happy to help make them grow!
> Point out relationship between useResource and useRef

- src/three-types.ts
specify type for `dispose` on `Object3DNode`, allows a function or null
> specify type for dispose on Object3DNode

- readme.md
Fixes the linked image in the section and a typo ( it's own state => its own state ).
> Fixes link to sandbox in "What does it look like?"

- src/reconciler.tsx
In `@react-spring/three` v9, the frameloop calls `invalidate` from within a global effect (r3f's terminology), but that call is ignored because of the broken logic in `renderLoop`. More specifically, the `running` variable is preventing rAF calls that would've otherwise kept the render loop going.
This fix makes sure to keep prevention of multiple rAF calls. 👍 
**Note:** react-spring v9.0.0-rc.3 won't work without this commit.
> fix: let global effects call `invalidate`

- src/reconciler.tsx
This fixes a major performance issue when using `@react-spring/three`
> fix: avoid calling rAF from renderLoop if already called

- readme.md
Hi, I've made slight improvements to the readme:
- Centered the heading:
- Remove the empy row above the table
- Add a table of content to the API section
> docs(readme): improve formatting

- src/three-types.ts
Add Vector2 to make glitch effects props available in Glitch (in react-postprocessing).
I am writing a `react-postprocessing` Glitch effect lib:
```jsx
import { GlitchEffect } from 'postprocessing'
import { ForwardRefExoticComponent, useMemo, useImperativeHandle, forwardRef } from 'react'
import { ReactThreeFiber } from 'react-three-fiber'
interface GlitchProps extends GlitchEffect {
delay: ReactThreeFiber.Vector2
}
const Glitch: ForwardRefExoticComponent<GlitchEffect> = forwardRef((props: GlitchProps, ref) => {
const effect = useMemo(() => new GlitchEffect(props), [props])
useImperativeHandle(ref, () => effect, [effect])
return null
})
export default Glitch
```
And `Vector2` is not present. This PR will add Vector2 type to r3f so I can use it later.
Here's what I want to add:
```ts
type …
```
> Add Vector2 to three-types

- src/canvas.tsx
This PR changes the "type" string in canvas pointerEnter events from camelcase to lowercase, as per the W3C spec:
https://w3c.github.io/pointerevents/#the-pointerenter-event
> Fix pointerEnter event.type capitalization

- src/reconciler.tsx
It fixes a crash when we use portals and (at least) this change happend in the scene tree:
Going from:
A <--portal--- B <----portal--- C
To:
D <--portal--- B <----portal--- C
(the replacement of A by D as a parentGroup of B is triggered by a prop change).
> Fix crash with createPortal.

- examples/src/demos/index.js
I wanted to open this PR to fix the white spots on white backgrounds. But I think the `Modifications` task is modifying my commit and breaking the `const InstanceMesh = {` formatting. (This is a guess).
How can this be avoided? My code does not have these line breaks. See below:
Anyway, here is the fix screenshots.
Before:
After:
> Fixing white spots on white backgrounds in examples

- examples/src/demos/dev/SelectiveBloom.js
In the master branch, this example does not seem to animate, do you remember if this was always the case?
> Fix SelectiveBloom.js warnings

- examples/src/demos/dev/Concurrent.js
The concurrent demo is broken since `<Dom>` was moved to Drei as `<HTML>`.
Currently, it shows this error:
> <Dom> was removed from lib and moved to Drei

- src/canvas.tsx
- src/reconciler.tsx
- src/three-types.ts
Following the existing examples of the `onClick` implementation, I extended the event handlers to support both `onDoubleClick` and `onContextMenu`.
The main reason for this PR is that I need to support "right-clicking" in my game. I was surprised to find that support for it didn't exist yet in R3F. The [corresponding handler in React](https://reactjs.org/docs/events.html#mouse-events) is `onContextMenu`. I looked through the discussions and didn't see any conversations about it yet, [however I did see one ](https://github.com/react-spring/react-three-fiber/discussions/499) about `onDoubleClick`. I figured I would add support for that event as well since I'll probably need it too 😉 
Please let me know if there is anything I can do to get this merged. Thanks again for this awesome library …
> Extended Click Event Handlers

- src/hooks.ts
Thanks for the great library! I've recently started using it with TypeScript, and I've noticed that the useUpdate hook returns a mutable ref of type `any` when a type argument is provided, so the returned ref doesn't have any meaningful type. This updates the return type to use the generic instead of `any` to preserve some type safety.
The rest of the changes came from husky/prettier.
> connect useUpdate generic argument type to its return value ref

- api.md
Following up from 064d9a3613a595a193d7fe2b3b9c7994cc8b7b9f, I was reading the `api.md` and saw that we didn't have examples for these new events yet.
Also, I made a small correction to the `forwardContext` example. It was using `myContext` before which isn't defined and may have been confusing to the reader.
> Api doc update

- api.md
When adding a component to a catalog via `extend()`, it may not be clear that they must be in camel case. This is conflicts with the stylistic standards of components which are pascal casing.  So it might be important to document this difference. This conversation was started in [discussion #587](https://github.com/react-spring/react-three-fiber/discussions/587).
> Notate that extended components use camel casing

- api.md
- examples/src/demos/dev/WebGL2.js
- package.json
- src/canvas.tsx
- src/components/generated.ts
- src/targets/shared/web/ResizeContainer.tsx
- src/targets/web.tsx
- yarn.lock
Proposed fix for #604.
Right now it does not build, since it needs `three >=118`.
Doing the update breaks some things.
> Fix for WebGL1 context creation

- src/canvas.tsx
Code sandbox link: https://codesandbox.io/s/r3f-shadowmap-prop-dv2jq
In the sandbox, VSM shadow maps should be selected:
```
shadowMap={{
enabled: true,
type: VSMShadowMap
}}
```
But the renderer is using the default type, `PCFShadowMap`, because the `enabled` and `type` props are being assigned to the `WebGLRenderer` itself, instead of to its `shadowMap` property.
> Fix object-style shadowMap prop not correctly applied

- src/canvas.tsx
- src/three-types.ts
A trick to have labeled tuples in some types, without forcing the user to use Typescript v4.
The TS v4 solution would be:
```
attachObject?: [target: string, name: string];
```
But this would break typings for users with TS v3. An hack to have them without breaking stuff is inferring params from a function, since it works also in older typescript.
Feel free to ignore this if it's too ugly (lol)
> Added Typescript tricks to have labeled tuples

- api.md
Just a typo: `Matrial` instead of `Material`
> Corret a typo in api.md

- recipes.md
Found this gem in https://spectrum.chat/react-three-fiber/general/invalidate-globally-except-for-orbitcontrols~27fcebaa-8b3a-43eb-b03d-d788b3b502a1
> Add camera control invalidation example

- src/canvas.tsx
Remove THREE scene dispose to avoid error in console
THREE js updated [here](https://github.com/mrdoob/three.js/commit/3a56aedf68934ba2f53690c73ff09b4e7a6f2139)
> Remove three scene dispose

- src/canvas.tsx
Fix #350 
The canvas-relative cursor coordinates given to the default raycaster used to be computed based on the position of the cursor in relation to the viewport (`clientX`/`clientY`) and the position of the canvas (`left`/`top`) provided by `useMeasure` (via `ResizeContainer.tsx`).
When the canvas moves on the screen without being resized or without the viewport being scrolled or resized, `useMeasure` has no way of knowing it, so `prepareRay` used to rely on potentially outdated canvas positions.
With this fix, `prepareRay` now uses the cursor's `offsetX` and `offsetY` positions, which are already canvas-relative coordinates, so the position of the canvas in the viewport no longer matters.
---
If I'm not 100% sure, but I think this fix means that raycasting will now work regardless of …
> Use offsetX/offsetY to compute mouse position in default raycaster

- src/canvas.tsx
This reverts part of the changes from https://github.com/pmndrs/react-three-fiber/pull/739
The `pointerOut` + `pointerLeave` logic branches were removed which introduced a bug where those events weren't firing on intersects.
> fixed pointerOut/pointerLeave on intersects

- markdown/api.md
As discussed on Discord, here's a small update to api.md to clarify the `useFrame` documentation a little.
- Specifically noted that _any_ non-zero priority will disable the automatic rendering
- Changed wording around a bit to make things a bit more straight-forward to grok
- Tweaked the main example given to be closer to valid component code
> Update api.md to clarify renderPriority usage

- src/hooks.ts
The previous check wasn't working, since a missing context apparently returns an empty object as a value - which is truthy.
I also fixed the linked doc
> Better error when using hooks outside of canvas

- markdown/api.md
- markdown/recipes.md
This adds a short explanation and example of how to get `react-three-fiber` working in Safari, since by default r3f will throw an error.
> Add recipe for Safari support

- readme.md
- Add `import type` to `Mesh` import in the Typescript example in README
- Fix props and component types
- Align callback `event` naming
> docs: fix types in typescript example

- src/renderer.tsx
@drcmda the addTail is broken since v5.0.0. The RAF would keep running with invalidateFrameLoop because the addTail hook was never invoked since repeat was always > 0.
This fixes the issue. 
Here is an example of the current issue :
https://codesandbox.io/s/r3f-invalidate-frameloop-fps-forked-ziep9?file=/src/Fps.js
> invalidate - prevent raf to keep running

- src/canvas.tsx
Instead of duplicating the options type, this passes it direct from `react-use-measure`.
> Pass ResizeOptions direct from react-use-measure

- src/renderer.tsx
resolves #925
The JS impl is correct & is identical to `ReactDOM.createPortal` however the type return from said func is `ReactPortal` which extends `ReactElement` there's debate  in https://github.com/DefinitelyTyped/DefinitelyTyped/issues/20942 as their impl being incorrect.
> refactor: add ReactNode as return type to createPortal

- src/hooks.ts
`useLoader` returns the same return type as the `THREE` loader returns, however, upon inspection (particularly with `GLTF` models) we're mutating the object to include `nodes` and `materials`, so in TS such as drei's `useGLTF` you can't use `nodes` or `materials` without bother. I thought we should probably fix that, we also don't need to check twice if object is defined, `buildGraph` returns data as is if there's no `object`.
I am aware this isn't the prettiest thing in the world so open on how to improve. I'm also making an assumption that only GTLF models have `scene` if that isn't the case, then I can change that too.
This also includes the solution proposed in https://github.com/pmndrs/react-three-fiber/pull/917, but the fix is extended to the `preload` function.
> fix: useLoader return type

- markdown/api.md
The spelling of `instantiated` was incorrectly written as `instanciated`.
Verified here: https://en.wiktionary.org/wiki/instanciated
> Corrected spelling of 'instantiated'

- src/canvas.tsx
- src/targets/native/canvas.tsx
Two issues found and fixed:
1. *Drop event arg from intersect() for onGotPointerCaptureLegacy* - The signature of `intersect` changed to remove the event arg but the legacy method `onGotPointerCaptureLegacy` for react native never got updated. This causes all touch events in native to fail.
2. *Replace `clientXY` with `offsetXY`* - There was a [helper function](https://github.com/pmndrs/react-three-fiber/pull/1020/files#diff-3e27362a51b34828c8b8cc6d91a746001f8615b8dadf942c1f74b01919c9a210L18) designed to shim the missing position properties on react native events but unfortunately it was shimming `clientY` and `clientY` whereas r3f [uses the offset coordinates](https://github.com/pmndrs/react-three-fiber/blob/d101f49f438aa2f485185fa9214a1c65957f483d/src/canvas.tsx#L357)
> Get touch events working with react native.

- src/canvas.tsx
This _patches_ https://github.com/pmndrs/react-three-fiber/issues/734.  I tested this on a physical Android and iOS device (can provide specs if needed) and the duplicate events are removed.  
"_explanation_"
for some reason, `event.type` is `undefined` on react-native.  this could make the conditional check falsely return positive for `event.type !== 'click'`, when in fact the event should have otherwise been a click (this is what happens for the bug ticket case).
since i'm not very clear on what this particular code chunk is doing - for example, what are we checking `state.current.captured` for?  & what is `state.current.captured` even doing? -  this could be a fix in the totally wrong place, i don't know.
> Patch event.type check for react native

- packages/fiber/src/three-types.ts
This adds `<fogExp2 />` which is currently missing.
> Add <fogExp2 />

- packages/fiber/src/web/Canvas.tsx
Anywhere we use `useLayoutEffect` will print some warnings when rendered server-side. See https://gist.github.com/gaearon/e7d97cdf38a2907924ea12e4ebdf3c85.
> Fix SSR warning with useLayoutEffect

- packages/fiber/src/core/renderer.ts
This PR fixes a new crash in v6 that happens in conjunction with `react-use-gesture` and an `onPointerCancel` event that's not defined on the mesh. I noticed that all of the other branches first check for the existence of `targetProp`, so it seems like the right thing to do here.
> Fix crash in applyProps when event is missing

- markdown/api.md
Remove unnecessary `;` in useLoader example.
> Fix example in api.md

- packages/fiber/src/core/renderer.ts
Since removeRecursive is no longer called. We miss removing any interactive child from rootState.internal.interaction
> make sure to recursively remove interactivity

- packages/fiber/src/core/renderer.ts
Fixes issue reported by #1197.
Issue seemed to be caused by the refactoring commit https://github.com/pmndrs/react-three-fiber/commit/e1d5efb4c00df05a89e57a8e8c4520c590d551cd. `"DoubleClick" `was previously covered by:
`objectKeys[i].includes('Click')`.
> add DoubleClick as a valid event handler

- babel.config.js
- packages/fiber/src/web/index.tsx
The React DevTools parses the semver string passed to `injectIntoDevTools` to detect the features available in the underlying `react-reconciler` instance (one such example can be found [here](https://github.com/facebook/react/blob/master/packages/react-devtools-shared/src/backend/renderer.js#L141)). These checks are used for instance to decide whether to enable support for hooks or suspense in the UI.
This PR changes the advertised version number to that of an equivalent React version to the react-reconciler library being used (right now the current Reconciler version is `0.26.2`, which I approximately mapped to `17.0.1`).
There are a few pros and cons to this change that I can think of, the obvious pros being that it makes the development experience generally better as it unlocks all the …
> Advertise a React-equivalent version number to the React DevTools

- packages/fiber/src/core/store.ts
It always return dpr[1] now when the arguments is [min, max] like [1, 2].
> Fix clamp in setDpr

- example/src/styles.tsx
- packages/fiber/src/core/events.ts
- packages/fiber/src/core/store.ts
Allows a mesh to properly handle capturing of several events.
Notice that only the first pointer is released.
https://user-images.githubusercontent.com/5003380/116914741-6d3a6400-ac4b-11eb-8907-814ba7baf8a9.mp4
Notice that all pointers are released.
https://user-images.githubusercontent.com/5003380/116914716-601d7500-ac4b-11eb-92e9-a2ed29a784e8.mp4
- add support for `event.target.hasPointerCapture`
- add `event.spaceX` and `event.spaceY` showing `state.mouse` THREE coordinates.
> Fix: better management of captured events

- packages/fiber/src/core/loop.ts
- packages/fiber/src/core/store.ts
Background: https://github.com/pmndrs/react-three-fiber/issues/1294
This change uses the `timestamp` argument in `advance(timestamp)` to update the clock when `frameloop = "never"`
Given the [implementation](https://github.com/mrdoob/three.js/blob/master/src/core/Clock.js#L40) of `THREE.Clock.getDelta()`, there isn't a way to have `getDelta()` return a value that is independent of `performance.now()`. So even with these changes, `clock.getDelta()` will always return 0. However, the delta provided in the `useFrame()` callback will be equal to the current timestamp minus the previous one.
With these changes, calling `advance(timestamp)` successively will look like this:
```js
advance(0)
useFrame(({ clock }, delta) => {
console.log(clock.getElapsedTime())   // 0
console.log(clock.getDelta()) …
```
> Update the clock when `frameloop = "never"`

- markdown/api.md
- packages/fiber/src/core/events.ts
- packages/fiber/src/core/store.ts
- packages/fiber/tests/web/web.events.test.tsx
It's useful to have the event object for onPointerMissed. Here's a couple of example use cases:
1. You might want to show some click feedback, like a particle effect around the pointer, to show that you saw the click but it didn't do anything. You need the co-ordinates of the event to do this.
2. In an object selection workflow, clicking on empty space might deselect everything - but ctrl-clicking empty space should have no effects. You need the `modifiers` property of the event to know what to do.
The event-handling code has the event object anyway - it passes it to individual objects' `onPointerMissed` handlers - so it's easy to pass it to the canvas as well.
> Give onPointerMissed an event argument

- packages/fiber/src/core/events.ts
- packages/fiber/tests/web/web.events.test.tsx
Clicks are MouseEvent, not PointerEvent, so they don't contain a pointerId at all, but they still need stopPropagation to work, to prevent clicks going to occluded objects. I've also added a test for using stopPropagation to stop a click event going to the occluded object.
See this discussion https://github.com/pmndrs/react-three-fiber/commit/d260376145c16f43fed97227a4f2e7d56a9dbbfa#r50677047 on the commit that introduced this bug.
> Fix the capture check for click events

- .changeset/popular-ligers-design.md
- example/src/demos/ContextMenuOverride.tsx
- example/src/demos/index.tsx
- packages/fiber/src/core/events.ts
- packages/fiber/src/web/events.ts
I noticed that all event listeners are set up as passive. This disallows calling `event.sourceEvent.preventDefault()` for `onContextMenu` listeners. As far as I understood only touch/pointer listeners should be set up as passive.
Some References:
- https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#improving_scrolling_performance_with_passive_listeners
- https://medium.com/@Esakkimuthu/passive-event-listeners-5dbb1b011fb1
> fix: passive event listener adjustments

- packages/test-renderer/src/createTestInstance.ts
- packages/test-renderer/src/helpers/testInstance.ts
resolves #1250 
We werent checking if `fiber.children` is defined. If it isn't we now just give an empty array to map over.
> fix: if children is undefined return an array to map with

- packages/fiber/src/core/events.ts
The logic was inverted for the case where the pointer wasn't captured at all (the common case), which resulted in stopPropagation silently failing in that case.
Committing also fixed some eslint-prettier complaints as a side-effect.
> Fix stopPropagation logic

- packages/fiber/src/web/Canvas.tsx
- packages/fiber/tests/web/canvas.test.tsx
This will allow a user of the library to get a reference to the rendered `canvas` so that they can do e.g. `canvas.captureStream()`.
Note: I'm not sure if the test is correct as I'm getting the following error when I try to run `yarn test` from the root. It's not entirely clear how to set the project up for development; maybe add some instructions to readme.md or contributing.md?
```
Warning: It looks like you're using the wrong act() around your test interactions.
Be sure to use the matching version of act() corresponding to your renderer:
// for react-dom:
import {act} from 'react-dom/test-utils';
// ...
act(() => ...);
// for react-test-renderer:
import TestRenderer from react-test-renderer';
const {act} = TestRenderer;
// ...
act(() => ...);
```
> feat: forward ref to canvas element

- package.json
- packages/test-renderer/src/createWebGLContext.ts
- yarn.lock
* fix: webglContext needs to be able to get VIEWPORT and SCISSOR_BOX
* resolves #1470
> RTTR doesn't work with r130 of THREE

- markdown/api.md
- packages/fiber/src/core/is.ts
- packages/fiber/src/core/renderer.ts
- packages/fiber/src/three-types.ts
- packages/fiber/tests/web/web.core.test.tsx
In addition to the `attach`, `attachArray` and `attachObject` properties it can be helpful if you can specify your own method. Either as a name of a method of the _parent instance_ or as a concrete function.
```jsx
<scene>
<mesh attachFunc="attach" detachFunc="remove" />
<mesh
attachFunc={(mesh, scene) => scene.add(mesh)}
detachFunc={(mesh, scene) => mesh.removeFromParent()}
/>
</scene>
```
I admit that this example is a bit weak in content - but it illustrates the API very well.
The usage scenarios are manifold, especially where objects that are not part of the scene are composed.
What do you think about it? 😃
> feat: add attach-func and detach-func callbacks

- packages/fiber/src/core/hooks.ts
Stemming from a [discord discussion](https://discord.com/channels/740090768164651008/745777196911689748/880429912295624714), we should probably throw an error if `useFrame` is used outside of a Canvas component if it throws an error anyway.
> useFrame now throws an error if used outside of the Canvas component

- packages/fiber/src/web/index.tsx
Without the `Partial` the `gl` props is practically unusable as it requires all the params to be present in the prop.
> Allow partial WebGLRenderer params

- packages/test-renderer/src/__tests__/is.test.ts
Using the myObj and MyArr previously created instead of using new ones for the last test.
All tests passing.
> is.test: 'is equal' test to use already declared obj and array.

- packages/fiber/tests/web/web.events.test.tsx
- packages/test-renderer/src/index.tsx
'RenderProps' is declared but its value is never read.ts(6133)
'events' is declared but its value is never read.ts(6133)
> chore: remove unused RenderProps and 'events'.

- packages/fiber/src/core/events.ts
- packages/fiber/tests/web/web.events.test.tsx
now when parent has OPM handler, child click won't trigger it
> change onPointerMissed behaviour

- packages/fiber/src/web/events.ts
I get a prettier warning on `events.ts`
`Replace `(Object.keys(names).reduce(⏎······(acc,·key)·=>·({·...acc,·[key]:·handlePointer(key)·}),⏎······{},⏎····)·as·unknown)` with `Object.keys(names).reduce((acc,·key)·=>·({·...acc,·[key]:·handlePointer(key)·}),·{})·as·unknown``
This update clears the prettier warning. All tests pass.
> Clear prettier warning on events.ts

- packages/fiber/src/core/hooks.ts
React Hook React.useLayoutEffect has a missing dependency: 'subscribe'. 
Either include it or remove the dependency array. 
_eslint react-hooks/exhaustive-deps_
> Fix eslint for 'exhaustive-rule.

- packages/fiber/tests/web/web.core.test.tsx
> tests(web):  `web.core.tests` updates

- packages/fiber/src/core/events.ts
- packages/fiber/src/core/store.ts
- packages/fiber/tests/web/web.events.test.tsx
Previously, unmounting the pointer capture target would not release its pointer capture. This would obviously cause problems when sending subsequent pointer events to it. This commit fixes the problem by storing the native (DOM) pointer capture target in the capturesMap so that it can be removed in removeInteractivity.
Adding a new test for pointer capture necessitated changing how the event props are copied in handleIntersects. The old code looked at the prototype (which should be PointerEvent) to find the props to copy, but in tests the pointerEventPolyfill is active and the prototype is MouseEvent, which meant none of the PointerEvent properties got copied. I've changed it to use for...in to look at the object's own properties and its inherited properties.
> fix(core): unmounting pointer capture target

- packages/fiber/package.json
- packages/fiber/src/core/hooks.ts
- packages/fiber/src/native/hooks.ts
- yarn.lock
With the release of [`suspend-react`](https://github.com/pmndrs/suspend-react), [`use-asset`](https://github.com/pmndrs/use-asset) is effectively deprecated. This PR does some minor refactoring when switching to it.
@drcmda, any planned changes I should know about? Should we publish & use an alpha with react-experimental's Cache?
> [v8] refactor(core): use-asset => suspend-react

- packages/fiber/src/three-types.ts
Fixes #1849 for r134 by removing definitions for THREE.ImmediateRenderObject.
> fix(types): remove definitions for ImmediateRenderObject

- packages/fiber/src/three-types.ts
Missing Float32BufferAttriute type causes Typescript error:
"Property 'float32BufferAttribute' does not exist on type 'JSX.IntrinsicElements'.ts(2339)"
similar issue as described in https://github.com/pmndrs/react-three-fiber/issues/238
Example of use of float32BufferAttribute
```jsx
<instancedBufferGeometry attach="geometry" instanceCount={count}>
<float32BufferAttribute
attachObject={['attributes', 'position']}
args={[positionArray, 3]}
/>
<instancedBufferAttribute
attachObject={['attributes', 'offset']}
args={[offsetArray, 3]}
/>
</instancedBufferGeometry>
```
> Fix missing type for Float32BufferAttribute

- packages/fiber/src/core/events.ts
- packages/fiber/src/core/store.ts
I was trying to solve #1863 and came across certain polishing that could be done quickly hence this PR which has the following changes:
1. Removes unused import of `InternalState` in events.ts 
2. Adds a better deprecation notice so it's more visible to people using the `sourceEvent` which is deprecated. 
3. Fix ts errors in store.ts for `lastEvent`
> Chore: Add more visible deprecation notice

- packages/fiber/src/core/renderer.ts
- packages/fiber/tests/web/web.core.test.tsx
As described in #1802, objects' event listeners can linger within the internal state despite never being mounted.
In [this example](https://codesandbox.io/s/r3f-duplicate-intersections-bug-8eq96?file=/src/App.js), `suspend` throws a promise that will revert the render, and the created instances are never mounted. However, event listeners are still attached as a side-effect, leading to duplication when React re-renders the suspended scene graph.
I undid some [reconciler changes](https://github.com/pmndrs/react-three-fiber/compare/5c4454...538c7c#diff-6dac2c0a764f293350e278dc10e97336f1d4b81379d1492eabf50462fe4d5752) from v7.0.8, moving initial attaching of handlers from `applyProps` (called by `createInstance`) back to `commitMount` -- reverting the regression. Events will only be updated …
> fix(core): attach handlers on mount to prevent duplication from Suspense

- packages/fiber/src/core/renderer.ts
Fixes #1569 by throwing an error if args are specified as anything other than an array. I believe that is the established pattern, unless we want to support something else.
Their example works with this syntax ([sandbox](https://codesandbox.io/s/react-three-mesh-ui-forked-hvcfg?file=/src/index.js)). See the below CSB builds for the error.
> chore(core): throw an error if an objects' args is not an array

- packages/fiber/src/core/events.ts
Fixes #1641 and #1502 by cleaning up captures and pointer events only when a captured pointer is released.
Previously, events would falsely trigger leave events and unhover an object as a side-effect.
> fix(events): cleanup captured pointers when released

- packages/fiber/package.json
This includes the `expo` unimodules as a dependency (renamed with SDK 43) so R3F is plug-and-play across configurations.
> chore(native): add expo unimodules as dep

- packages/fiber/src/core/renderer.ts
Safely checks whether `performance` is defined and will fallback to `Date#now` in environments without browser built-ins like Node.
> fix(core): safely allocate `now`

- packages/fiber/src/core/renderer.ts
Respects color preferences made from anywhere by checking the renderer's outputEncoding instead of our internal `linear` prop. This will ensure correct behavior for renderers or properties coming from the `gl` prop.
> fix(core): respect encoding preferences from `gl` when converting colors

- packages/fiber/src/core/renderer.ts
- packages/fiber/tests/web/web.core.test.tsx
Fixes #1937 by binding inherited event handlers when swapping instances (when reconstructing due to args change, etc.).
[Issue recreation](https://codesandbox.io/s/loving-tharp-kfksi) | [Fixed w/PR](https://codesandbox.io/s/condescending-spence-cdn3b?file=/src/App.js)
> fix(core): rebind handlers for swapped instances

- package.json
- packages/fiber/package.json
- packages/fiber/src/three-types.ts
- yarn.lock
Fixes https://github.com/pmndrs/drei/issues/704
> Remove types not part of THREE namespace anymore

- packages/fiber/src/core/store.ts
- packages/fiber/src/web/index.tsx
Continues #1976 by deprecating the `vr` and `modes` props as their respective features will work automatically with R3F v8 and React 18.
> chore: deprecate props removed in v8

- package.json
- packages/fiber/package.json
- yarn.lock
Related: https://github.com/pmndrs/react-three-fiber/issues/1972#issuecomment-1016396098
Unpins `expo-gl` and marks `expo-asset` as a peer dependency (included as a dependency of `expo`).
> fix(native): unpin and correctly mark peer deps

- packages/fiber/src/core/loop.ts
- packages/fiber/src/core/store.ts
Exposes `XRFrame`, containing pose data while rendering in XR.
Related links:
- https://developer.mozilla.org/en-US/docs/Web/API/XRSession/requestAnimationFrame
- https://developer.mozilla.org/en-US/docs/Web/API/XRFrame
> feat(core): pass XRFrame to subscribers

- docs/getting-started/installation.mdx
- docs/getting-started/introduction.mdx
- package.json
- packages/fiber/package.json
- yarn.lock
Fixes #2013 and #1858.
Expo libraries should not be included as NPM dependencies but be installed after `expo` modules and before R3F (so NPM doesn't auto-install peer deps). I've updated the docs to reflect and include a workflow for expo-cli and react-native CLI.
> fix(native): move expo-gl to peer dep, add complete expo modules instructions for RN and expo-cli

- docs/API/render-function.mdx
- packages/fiber/package.json
- yarn.lock
Looks like `utility-types` is also unused, something I can remove too?
> fix: remove unused resize-observer-polyfill dep

- docs/API/objects.mdx
The extend function will cause a type error unless the user adds its declaration to the modules. I added an example in the documentation.
> Typescript example for the extend function

- packages/fiber/src/index.tsx
- packages/test-renderer/src/types/internal.ts
Fix type imports (`BaseInstance`, `LocalState` and `RootState`) from **@react-three/fiber** in **@react-three/test-renderer**.
See: https://github.com/pmndrs/react-three-fiber/discussions/2061
> 🐛 Fix type imports in Test Renderer

- docs/advanced/pitfalls.mdx
State slicing happens in the first argument, not the second.
> fix store subscription argument order

- packages/fiber/src/three-types.ts
TS isn't happy about using `Object3D` as intrinsic element (`Property 'object3D' does not exist on type 'JSX.IntrinsicElements'`), seems to work otherwise 
```tsx
<object3D />
```
> fix: add Object3D to IntrinsicElements

- package.json
- packages/fiber/package.json
The built declaration files depend on `@types/react-reconciler`. Here are the build errors without it:
```
.yarn/__virtual__/@react-three-fiber-virtual-af98807581/0/cache/@react-three-fiber-npm-7.0.26-699ff8d26f-72548c6d2a.zip/node_modules/@react-three/fiber/dist/declarations/src/core/renderer.d.ts:2:24 - error TS7016: Could not find a declaration file for module 'react-reconciler'. 'C:/Users/nbier/Documents/stash/test-react-three-fiber/.yarn/__virtual__/react-reconciler-virtual-c1be2dd0c5/0/cache/react-reconciler-npm-0.26.2-284c00acc7-2ebceace56.zip/node_modules/react-reconciler/index.js' implicitly has an 'any' type.
Try `npm i --save-dev @types/react-reconciler` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-reconciler';`
2 import Reconciler from …
```
> Move @types/react-reconciler to dependencies

- example/src/demos/MultiMaterial.tsx
- packages/fiber/src/core/utils.ts
Restores v7's `attachArray` behavior with unified attach (see #1912).
> refactor(core): create an array when indexing with attach

- packages/fiber/src/native/Canvas.tsx
- packages/fiber/src/web/Canvas.tsx
Without this change the flag will be passed to the `div` element rather than the `Canvas` element. Which means that the flag basically does nothing in production, which is why you see no effect in versions >= 8.0.2 when using this flag on web.
> fix(web): pass legacy attribute to canvas

- packages/fiber/src/core/index.tsx
- packages/fiber/src/core/utils.ts
- packages/fiber/src/native/Canvas.tsx
- packages/fiber/src/web/Canvas.tsx
- packages/fiber/tests/web/canvas.test.tsx
Fixes #1163 where we regressed from using an isomorphic effect in canvas to play nice with react ssr.
> fix(web): use isomorphic effects in canvas for react ssr

- packages/fiber/src/core/hooks.tsx
- packages/fiber/src/core/utils.ts
- packages/fiber/src/native/Canvas.tsx
- packages/fiber/src/web/Canvas.tsx
Continues #2110. ([onPointerMissed codesandbox](https://codesandbox.io/s/quirky-montalcini-bk2jlm?file=/src/App.js))
Makes useMemoizedFn more generic to allow re-use in useFrame.
> refactor: useMemoizedFn => useMutableCallback

- packages/fiber/src/core/index.tsx
- packages/fiber/src/core/store.ts
- packages/fiber/tests/core/renderer.test.tsx
Closes #2211 
The private key list was doing the opposite of what was intended (i think), and was only copying the things from the root state that was in the list. Meaning the get & set was being copied from the parent store.
Made some assumptions about what keys should be private, based on the previous behaviour before b0a16c95da6a97b5af82a0db8a9d397f1593177c
> fix: state copy respect private keys

- docs/API/hooks.mdx
Small docs change that indents the `function App()` in the hooks doc so that it's more obvious that the function is supposed to be nested inside of `<Foo>`
> Indent function in hooks doc

- packages/fiber/src/core/renderer.ts
Previously it did not work (would call .splice on null) if the array didn't already exist.
**NB** this PR is against the v7 branch. My project won't be able to update to v8 for at least the next year owing to the React dependency, so we'll be continuing to patch bugs and develop the event system in the v7 version.
> fix(core) insertBefore supports attachArray

- packages/fiber/src/core/renderer.ts
react-three-fiber raises an error when its renderer encounters an element type it does not know from the THREE namespace. The error message includes a link to the documentation of `extend`; this link was unfortunately 404ing.
This PR fixes the issue by updating the link.
> Fix link to `extend` documentation

- docs/tutorials/typescript.mdx
should pass `ref` to props `ref`
> docs(tutorials/typescript): fix typo

- packages/fiber/src/core/index.tsx
In some cases (that are still not really clear to me), when an error occur when rendering react-reconciler might fire onRecoverableError, which is a new parameter in createContainer. Unfortunately the typings doesn't yet support the new parameters, so they have to be monkey patched.
More info: https://github.com/facebook/react/pull/23207
> fix(core): Add support for recoverable errors

- packages/fiber/src/core/hooks.tsx
useLoader won't correctly type nodes etc. from buildGraph if the type doesn't match @types/three's GLTF type. I've relaxed this a bit so libraries like three-stdlib and @react-three/drei will get correct types more inline with the implementation.
> fix(hooks): correctly infer useLoader type

- packages/fiber/src/web/Canvas.tsx
- packages/fiber/tests/core/events.test.tsx
- packages/fiber/tests/web/__snapshots__/canvas.test.tsx.snap
This PR is fixing this [issue](https://github.com/pmndrs/react-three-fiber/issues/1684)
I added a separate div to control size of canvas. In this case the size of new inner div doesn't depend on other styles that customize outer div "positions".
> fix (#1684): add div container for canvas size handling

- packages/fiber/package.json
- packages/fiber/src/native/Canvas.tsx
- packages/fiber/src/web/Canvas.tsx
Continues #2266
Cleans up ref leftovers in canvas.
> refactor(Canvas): react-merge-refs => useImperativeHandle

- packages/fiber/src/core/renderer.ts
Fixes #2250 by reverting a fix made prior to React 18 as reported in #1551 (see #1902 and https://github.com/pmndrs/react-three-fiber/commit/5eafc6a522d00afaa3858793e83ac06843a9d230).
This PR moves attach logic to `commitMount` when we know for sure instances are ready to mount.
[2250 sandbox](https://codesandbox.io/s/append-bug-forked-rhjx6m) | [1551 sandbox](https://codesandbox.io/s/material-suspense-bug-forked-nquc9g)
> fix(core): don't handle attach on visibility change

- packages/fiber/src/core/index.tsx
- packages/fiber/src/core/utils.ts
- packages/fiber/tests/core/renderer.test.tsx
Fixes #2272 by using a more lenient guard for `THREE.ColorManagement` checks. Will also side-step runtime checks by safely traversing `THREE => THREE.ColorManagement => THREE.ColorManagement.legacyMode` before mutating in the guard.
> fix(core): safely set ColorManagement

- packages/test-renderer/src/index.tsx
Mirrors the null check in update and other methods.
> fix(test-renderer): safely access mock root in getInstance

- docs/tutorials/v8-migration-guide.mdx
I fixed the small error of v8 Migration Guide.
See  #2172
> :pencil2: fix small error in doc

- packages/fiber/src/core/index.tsx
Uses the shared internal react version when initializing dev tools as does [`react-dom`](https://github.com/facebook/react/blob/3133dfa6ee8d1a8355c0249007176955d4b7d6b0/packages/react-dom/src/client/ReactDOM.js#L227).
> fix(core): report react's internal version to devtools

- readme.md
minor issue, anybody knowledgeable would find out where the problem is before running an example, nonetheless should be fixed
> Readme file missing type for typescript example

- example/src/demos/Gltf.tsx
- example/src/demos/Lines.tsx
- example/src/demos/MultiMaterial.tsx
- example/src/demos/MultiView.tsx
- example/src/demos/ResetProps.tsx
- example/src/demos/Test.tsx
- example/src/demos/ViewTracking.tsx
- packages/fiber/src/core/events.ts
- packages/fiber/src/core/renderer.ts
- packages/fiber/src/core/utils.ts
- packages/fiber/src/native/events.ts
- packages/fiber/src/web/events.ts
Tidies examples for StrictMode and removes leftovers from rounds of refactors in the core.
> chore: cleanup examples and leftovers

- packages/fiber/src/core/renderer.ts
- packages/fiber/tests/core/renderer.test.tsx
Fixes an issue where objects won't have their child attachments copied over.
[Instances (before)](https://codesandbox.io/s/rj6uoo) | [Instances (now)](https://codesandbox.io/s/zo47oc)
> fix(core): copy attached children on swap

- packages/fiber/src/core/renderer.ts
- packages/fiber/src/core/utils.ts
- packages/fiber/tests/core/renderer.test.tsx
Reverts the change in #2296 where instances were no longer unconditionally prepped when entering a new R3F root (see https://github.com/pmndrs/react-three-fiber/pull/2296#discussion_r885138009).
This PR accounts for my above nit by only overwriting essential, root-specific local state to allow for foreign instances to be re-used between roots.
> fix(core): always prepare primitives

- packages/fiber/src/core/renderer.ts
- packages/fiber/src/core/utils.ts
- packages/fiber/tests/core/renderer.test.tsx
- packages/test-renderer/src/createTestInstance.ts
- packages/test-renderer/src/types/internal.ts
Reverts #2296 and #2305 where attached elements were incorrectly allowed in different areas of the tree and between different roots (related: #2294).
> refactor: revert multi-attach

- packages/fiber/src/core/renderer.ts
- packages/fiber/tests/core/renderer.test.tsx
Fixes #2315, by reverting #2268 where attach happens between useLayoutEffect and useEffect.
As a result, #2250 is unfixed for now, but the above issue is still present for event handlers (should be inconsequential outside of attach).
> fix(core): revert #2268 for uLE timings

- docs/getting-started/installation.mdx
Correct `has` to `as` in:
> Getting started with React Three Fiber is not nearly **has** hard as you might have thought
> Fix typo in `installation.md`

- packages/fiber/src/core/index.tsx
Restarts R3F's internal render loop on session end to resume rendering outside of sessions.
> fix(core): resume render loop on session end

- packages/fiber/src/core/index.tsx
- packages/fiber/src/core/store.ts
- packages/fiber/src/native/Canvas.tsx
- packages/fiber/src/web/Canvas.tsx
- packages/fiber/tests/core/hooks.test.tsx
- packages/test-renderer/src/__tests__/RTTR.hooks.test.tsx
Related to https://github.com/pmndrs/drei/issues/944
This change adds `top` and `left` properties to `state.size` in web and native implementations (extra eyes on the native change appreciated).
For now, I've maintained the order of arguments to `setSize` for better backwards compatibility.
When publishing the next major version of r3f, I would recommend re-ordering arguments to the more standard `width, height, top, left, updateStyles` order or even better, switching to an object argument with a shape like `Size & { updateStyles?: boolean }` to disambiguate between positional arguments of the same type and to make the interface more flexible to this sort of change in the future.
> Expose position information on `state.size`

- packages/fiber/src/three-types.ts
This PR directly exposes all the r3f-specific React element types, instead of directly augmenting `JSX.IntrinsicElements`. `JSX.IntrinsicElements` still gets augmented, so it is fully backwards-compatible:
```ts
export interface ThreeElements {
// ...
}
declare global {
namespace JSX {
interface IntrinsicElements extends ThreeElements {}
}
}
```
This would be very useful for libraries that need to map over, or validate against r3f elements, like `@theatre/r3f` or `@react-spring/three`. Currently the only option is to use `JSX.IntrinsicElements`, which results in incorrect types that are way too broad and include other elements too, like those from `react-dom`. Furthermore since `JSX.IntrinsicElements` is huge, it can easily result in types that are either too complex for the type checker …
> Expose ThreeElements interface

- packages/fiber/src/core/utils.ts
Mirrors https://github.com/reduxjs/react-redux/pull/1444 with a check for react-native in `useIsomorphicLayoutEffect`, so `useEffect` is only used server-side.
> fix: use useLayoutEffect in native

- packages/fiber/tests/core/events.test.tsx
- packages/fiber/tests/core/hooks.test.tsx
- packages/fiber/tests/core/renderer.test.tsx
- packages/fiber/tests/native/hooks.test.tsx
- packages/fiber/tests/setupTests.ts
- packages/shared/setupTests.ts
- packages/test-renderer/src/__tests__/RTTR.hooks.test.tsx
- packages/test-renderer/src/createWebGLContext.ts
- packages/test-renderer/src/index.tsx
- tsconfig.json
This PR corrects several typing errors and removes `ts-ignore` from test files.
> fix: tests typecheck

- packages/fiber/src/core/renderer.ts
Eases crash behavior when invalid JSX is passed as text (e.g. stray characters).
> fix(renderer): warn on text instance, null check on instance create

- docs/getting-started/introduction.mdx
- docs/tutorials/typescript.mdx
- example/src/demos/Lines.tsx
- example/src/demos/Pointcloud.tsx
- example/tsconfig.json
- example/typings/global.d.ts
- packages/fiber/tests/core/renderer.test.tsx
- readme.md
This PR replaces all cases where we had the old approach of typing:
```
declare global {
namespace JSX {
interface IntrinsicElements extends ThreeElements {}
}
}
```
with the new one:
```
declare module '@react-three/fiber' {
interface ThreeElements {
myMesh: Object3DNode<MyMesh, typeof MyMesh>
}
}
```
> fix: replace IntrinsicElements with ThreeElements

- docs/tutorials/v8-migration-guide.mdx
- package.json
- packages/fiber/package.json
- packages/fiber/src/core/index.tsx
- packages/fiber/src/core/loop.ts
- packages/fiber/src/core/stages.ts
- packages/fiber/src/core/store.ts
- packages/fiber/src/core/utils.ts
- packages/fiber/tests/web/__snapshots__/canvas.test.tsx.snap
- packages/test-renderer/package.json
- yarn.lock
Bumps the three peer dep and eagerly sets `THREE.ColorManagement`, reverting #2273.
r141 uses augmented WebXR types from `@types/webxr`, so we'll also want to coordinate majors around three-stdlib and Drei.
> [v9] refactor(core)!: always set colormanagement, use r141 WebXR types

- packages/fiber/src/core/index.tsx
- packages/fiber/src/core/loop.ts
As @madou noted [here](https://github.com/pmndrs/drei/issues/944#issuecomment-1193931385), the `clientTop` used in the previous MR around
Seems this would only effect users of direct `createRoot` and not `Canvas` but still worth correcting.
Did a small amount of boyscoutting to remove `let`s and improve types here. The notable change is using a typeguard to throw at the top of `createRoot` if the supplied element is not a canvas. This allows cleaner typings after the guard. Specifically, the same `canvas` variable is later passed to `createRendererInstance` where it is cast to `HTMLCanvasElement` and I assume would fail if the cast is inaccurate. Happy to revert this part of the change if it is not desired.
> Fix: initial canvas size computation in createRoot

- packages/fiber/src/core/hooks.tsx
While useLoader will never use a user defined manager, being explicit here with the type helps with type errors elsewhere.  Especially in the useGLTF class of drei.
https://github.com/pmndrs/drei/issues/894
> Fixed type for loader class in useLoader

- packages/fiber/src/three-types.ts
Closes #2374 
Also supports `readonly` variants of other vectors and `THREE.Matrix4`
> Accept readonly arrays for vector props

- .changeset/lemon-glasses-kneel.md
- packages/fiber/src/native/Canvas.tsx
- packages/fiber/src/web/Canvas.tsx
- Renames the somewhat generically named `Props` interfaces from both `Canvas.tsx` modules to a more specific `CanvasProps`.
- The (minor) unrelated formatting changes were, I think/hope, Prettier picking up the repository's `.prettierrc`.
- Changeset included.
> Rename `Props` to `CanvasProps`

- docs/API/canvas.mdx
- docs/advanced/pitfalls.mdx
- docs/tutorials/how-it-works.mdx
- example/src/demos/Animation.tsx
- example/src/demos/AutoDispose.tsx
- example/src/demos/ClickAndHover.tsx
- example/src/demos/MultiRender.tsx
- example/src/demos/Selection.tsx
- example/src/demos/SuspenseMaterial.tsx
- packages/fiber/tests/core/hooks.test.tsx
- packages/fiber/tests/core/renderer.test.tsx
- packages/test-renderer/README.md
- packages/test-renderer/src/__tests__/RTTR.core.test.tsx
- packages/test-renderer/src/__tests__/RTTR.methods.test.tsx
Removes usage of aliases in docs and examples such as `BoxBufferGeometry` in favor of `BoxGeometry`.
> docs: remove usage of *BufferGeometry

- packages/fiber/src/three-types.ts
r144 deprecates usage of `BoxBufferGeometry` aliases in favor of `BufferGeometry`. As per three deprecation policy, these will be completely removed in r154, so preferring to remove any references to them now. In JS-land, this would emit a warning.
> fix!: remove *BufferGeometry type aliases

- packages/fiber/src/core/renderer.ts
Prefers to check against instances' prototypes for whether they are valid Geometry/Material attach targets. This includes primitives and no longer relies on elements' semantics.
> fix: check instance prototype for auto-attach

- packages/fiber/src/core/renderer.ts
Prefers to check against instances' prototypes for whether they are valid Geometry/Material attach targets. This includes primitives and no longer relies on elements' semantics.
> feat(core): check instanceof for auto-attach

- packages/fiber/src/core/renderer.ts
- packages/fiber/tests/core/renderer.test.tsx
Swaps over R3F-managed children of primitives when reconstructing. This lets their `object` prop predictably keep declarative children.
```js
<primitive object={foo ? object1 : object2}>
<mesh />
<material />
</primitive>
```
> fix(core): handle primitive children on reconstruct

- packages/fiber/src/core/renderer.ts
Adds back a safety valve removed in error from #2452.
> fix(core): null-check instance.children on reconstruct

- docs/advanced/scaling-performance.mdx
looks like a typo to me, "id" is not defined.
I think "i" makes the most sense given what the docs say getMatrixAt does.
docs for getMatrixAt: https://threejs.org/docs/?q=instanced#api/en/objects/InstancedMesh
> fix: typo, changed "id" to "i"

- packages/fiber/src/core/renderer.ts
- packages/fiber/tests/core/renderer.test.tsx
Fixes #2469 by ensuring that containers passed to `createPortal` are mounted and managed by R3F before appending. In this case, React removes the parent container and then tries to re-append its child container, which is undefined behavior.
> fix(core): don't append to unmounted containers

- packages/fiber/src/three-types.ts
Right now the @react-three/drei declaration files fail to type-check with these errors:
<details>
<summary>Errors</summary>
```
node_modules/@react-three/drei/core/AccumulativeShadows.d.ts:31:226 - error TS2344: Type 'string | undefined' does not satisfy the constraint 'string | number | symbol'.
Type 'undefined' is not assignable to type 'string | number | symbol'.
31 export declare const AccumulativeShadows: React.ForwardRefExoticComponent<Pick<Omit<ReactThreeFiber.ExtendedColors<ReactThreeFiber.Overwrite<Partial<THREE.Group>, ReactThreeFiber.NodeProps<THREE.Group, typeof THREE.Group>>>, ReactThreeFiber.NonFunctionKeys<{
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
32     position?: ReactThreeFiber.Vector3 | undefined;
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
...
39     dispose?: (() => …
```
> fix(types): @react-three/drei declaration files

- docs/API/events.mdx
- docs/tutorials/events-and-interaction.mdx
- packages/fiber/src/core/renderer.ts
- packages/fiber/src/core/utils.ts
- packages/fiber/src/three-types.ts
Follow-up to https://github.com/pmndrs/react-three-fiber/pull/2308#issuecomment-1153015467. Removes the `onUpdate` prop in favor of `useMemo` or `useEffect`.
> [v9] refactor: remove onUpdate prop

- packages/fiber/src/core/renderer.ts
- packages/fiber/src/core/utils.ts
- packages/fiber/tests/core/renderer.test.tsx
Depends on #2465, fixes #2250.
Moves `attach` and interactivity to `handleContainerEffects` which will fire when trees are linked and finalized. This ensures that effects are not duplicated due to suspense and complete outside of commit, so we're never late and present an incomplete tree.
I've updated the CSB to highlight the intricacies throughout the reconciler lifecycle: https://codesandbox.io/s/scrgbc. Should fire `attach` (uuid must match ref and thus be current), `useLayoutEffect` (ensures the view is completed before presenting), then the parent is reconstructed from scratch so children will `detach` and `attach`.
I've also added an `isHidden` property to instances to make sure we don't handle `attach` or `detach` for instances that weren't hidden by React. This could similarly …
> [v9] fix: handle container effects on completed trees, track instance visibility

- docs/API/additional-exports.mdx
- packages/fiber/src/core/hooks.tsx
- packages/fiber/tests/core/hooks.test.tsx
Implements #2467. Adds a `useInstanceHandle` hook that accepts a ref to an R3F element and returns its local state. This would be equivalent to `ref.current.__r3f`, which should be avoided in production code.
```jsx
const ref = React.useRef()
const instance = useInstanceHandle(ref)
React.useLayoutEffect(() => {
instance.parent.foo()
}, [])
<group ref={ref} />
```
> **Note**: this is an escape hatch to react-internal fields. Expect this to change significantly between versions.
> feat(hooks): useInstanceHandle

- docs/API/additional-exports.mdx
- packages/fiber/src/core/loop.ts
Continues #2351. Exposes global effects for when manually driving a loop via `advance`.
```js
function flushGlobalEffects('before' | 'after' | 'tail', timestamp: number): void
//
flushGlobalEffects('after', performance.now())
```
> feat(loop): `flushGlobalEffects` for manual loop manipulation

- packages/fiber/src/core/index.tsx
- packages/test-renderer/src/index.tsx
- packages/test-renderer/src/types/public.ts
R3F exports `React.unstable_act` as `act` which is not defined in `@types/react`. This PR can possibly be picked into DefinitelyTyped, but it's notable that `act` will inherit the return value of the promise passed to it:
```tsx
const store: UseBoundStore<RootState> = await act(() => root.render(<Scene />))
console.log(store.getState()) // RootState
```
> [v9] fix!: type unstable_act

- packages/fiber/src/core/index.tsx
Follow-up to #2490. Prefers to keep React types local to avoid clashing with user-defined global React types.
> [v9] fix(types): don't declare unstable_act

- packages/fiber/src/core/events.ts
- packages/fiber/src/core/utils.ts
Prior to this change, this code would throw an error when run inside of a WebWorker, since window is not defined inside of webworkers.
This prevented us from using R3F inside of an offscreen canvas in a webworker.
See https://stackoverflow.com/questions/71587025/cant-use-offscreencanvas-with-react-three-fiber for an example.
> Use self to get global context before window in getEventPriority.

- package.json
- packages/fiber/package.json
- packages/fiber/src/core/utils.ts
- packages/fiber/src/native/Canvas.tsx
- packages/fiber/src/web/Canvas.tsx
- packages/fiber/tests/core/utils.test.ts
- yarn.lock
Follow-up to #2509, uses [pmndrs/its-fine#useContextBridge](https://github.com/pmndrs/its-fine#useContextBridge).
> refactor: pull context bridge from its-fine

- docs/advanced/pitfalls.mdx
- Flips the order of isPending and startTransition in the return value to reflect the updated API
- Removes suggestion to use experimental React and set canvas as concurrent
> Update concurrency info on Pitfalls docs page

- packages/fiber/package.json
- yarn.lock
Follow-up to https://github.com/pmndrs/its-fine/pull/11 to prevent R3F from creating roots from scratch.
> fix(Canvas): prevent remount on context update

- packages/fiber/package.json
- yarn.lock
Follow-up to https://github.com/pmndrs/its-fine/pull/13. Hardens context against cross-renderer suspense bubbling.
> chore: upgrade bridge to harden suspense behavior

- packages/fiber/package.json
- yarn.lock
Updates its-fine to work-around older CRA installs (see https://github.com/pmndrs/its-fine/pull/14, https://github.com/pmndrs/its-fine/issues/12, https://github.com/facebook/create-react-app/issues/10356).
> fix: upgrade deps to work-around CRA

- packages/fiber/package.json
- yarn.lock
Fixes #2533. Dev-only fields were incorrectly overwritten in production. Mirrors https://github.com/pmndrs/its-fine/pull/15.
> fix: upgrade deps

- packages/fiber/src/core/events.ts
- packages/fiber/src/core/loop.ts
- packages/fiber/src/core/utils.ts
Related to #2540 ongoing discussion
Same principle but targeted at V8
> fix: prefer named functions, for loops in hot paths

- packages/fiber/src/core/events.ts
- packages/fiber/src/core/loop.ts
Following the discussion here https://discord.com/channels/740090768164651008/740093168770613279/1023859404111613962
I went to add a name function to remove this anonymous function from the performance tool report 
I also thought that we could replace the forEach with for loops where applicable. 
With the for loop there isn't a need to use a named function at all in the end. 
So I went through the files and replaced the forEach loop that looked safe to replace. 
I'm expecting a gain of 1µs per frame with that 
The perf gain is probably neglectable but it removes some noise from the performance and also use less memory for one of them that was creating a new array on each call ( cancelPointer )
> [v9] fix: prefer named functions, for loops in hot paths

- packages/fiber/src/core/utils.ts
Ensures that children added via `attach` have `onUpdate` work post mount.
> fix: call onUpdate for attached children prop update

- packages/fiber/src/core/index.tsx
Prefers the stricter `JSX.Element` type to play nice with `createPortal` in lambda components or as the root element.
> fix(createPortal): use correct JSX type

- packages/fiber/src/core/utils.ts
- packages/fiber/tests/core/renderer.test.tsx
Invalidates pierced props whenever their root is changed (e.g. `map-needsUpdate` in `<material map={map} map-needsUpdate />`.
> fix: invalidate pierced props

- packages/fiber/src/core/utils.ts
- packages/fiber/tests/utils.test.ts
> [v9] fix: invalidate pierced props

- packages/fiber/package.json
- packages/fiber/src/core/events.ts
- packages/fiber/src/core/hooks.tsx
- packages/fiber/src/core/index.tsx
- packages/fiber/src/core/renderer.ts
- packages/fiber/src/core/stages.ts
- packages/fiber/src/core/store.ts
- packages/fiber/src/core/utils.ts
- packages/fiber/src/index.tsx
- packages/fiber/src/native.tsx
- packages/fiber/src/native/events.ts
- packages/fiber/src/web/events.ts
- packages/fiber/tests/index.test.tsx
- packages/fiber/tests/utils.test.ts
- packages/test-renderer/src/fireEvent.ts
- yarn.lock
Migrates to Zustand v4 to unpin and hopefully de-dup user-land installs. Also exports a `RootStore` type alias.
> [v9] refactor(types)!: upgrade Zustand to v4

- packages/fiber/src/core/events.ts
- packages/fiber/src/core/hooks.tsx
- packages/fiber/src/core/index.tsx
- packages/fiber/src/core/loop.ts
- packages/fiber/src/core/stages.ts
- packages/fiber/src/core/store.ts
- packages/fiber/src/index.tsx
- packages/fiber/src/native.tsx
Exports public-facing types from the core, namely events and state keys.
> [v9] refactor(types): export public types

- packages/fiber/src/core/events.ts
- packages/fiber/tests/core/events.test.tsx
Fixes for #2553 and #2248, including test. A pointerleave event is still raised if you do not manually release the pointer capture, even if the pointer is still in fact over the element, as a lostpointerevent is still handled by calling cancelPointer if there is still a capture registered - but at least with this small change the desired behavior can be acheived.
> fix: pointer events and pointer capture

- packages/fiber/src/core/events.ts
sort by distance even when root state is undefined.
This solves some sorting bugs for me for complicated interaction structures.
> fix(events): sort by distance on undefined roots

- packages/fiber/src/core/hooks.tsx
- packages/fiber/tests/core/hooks.test.tsx
Fixes #2579 by inferring the loader prototype and passing it to extensions.
```ts
import { useLoader } from '@react-three/fiber'
import { MTLLoader, OBJLoader } from 'three-stdlib'
const materials = useLoader(MTLLoader, '/path/to/materials.mtl')
const object = useLoader(OBJLoader, '/path/to/geometry.obj', (loader) => {
materials.preload()
loader.setMaterials(materials)
})
```
> fix(useLoader): make better use of generics for extensions

- packages/fiber/src/core/index.tsx
- packages/fiber/src/core/loop.ts
- packages/fiber/src/index.tsx
- packages/fiber/src/native.tsx
Addresses https://github.com/pmndrs/react-three-fiber/pull/2559#discussion_r998652964, follow-up to #2481.
> fix(loop): export flush methods and types

- packages/fiber/src/core/events.ts
- packages/fiber/src/core/index.tsx
- packages/fiber/src/three-types.ts
Events spread their non-atomic properties to handlers, but aren't typed accordingly. A work-around would be to directly access `nativeEvent`.
```ts
<mesh
onClick={(event: ThreeEvent<MouseEvent>) => {
console.log(event.nativeEvent.shiftKey)
console.log(event.shiftKey) // TS2339: Property 'shiftKey' does not exist on type 'ThreeEvent'.
}}
/>
```
> fix(events): type spread event props

- readme.md
small typo in the link to react-three-rapier
> Fix broken link to react-three-rapier

- docs/API/hooks.mdx
> Very small typo (useFrame)

- packages/fiber/src/core/reconciler.ts
- packages/fiber/src/three-types.ts
Addresses some type regressions with `{}` and `children` investigated in #2668.
> fix(types): don't overwrite types of infer fallback

- packages/fiber/src/core/renderer.ts
- packages/fiber/tests/core/renderer.test.tsx
Would this be a viable solution to #2679 ?
I'm least confident about the naming of `autoRemovedBeforeAppend` :D
> fix: Primitives are incorrectly swapped on key change in maps #2679

- packages/fiber/src/core/reconciler.ts
- packages/fiber/tests/renderer.test.tsx
- packages/test-renderer/src/__tests__/__snapshots__/RTTR.core.test.tsx.snap
Mirrors https://github.com/pmndrs/react-three-fiber/pull/2680 in the new architecture.
> [v9] fix(core): correctly swap map elements on invalidate

- packages/fiber/src/core/utils.ts
- packages/fiber/tests/core/renderer.test.tsx
Mirrors https://github.com/pmndrs/react-three-fiber/pull/2465#discussion_r967339200 from v9. Correctly sets atomic props' defaults where unset by three.js.
> fix(core): don't use three.js math identity for HMR

- packages/fiber/src/core/hooks.tsx
When trying to use `@types/three@0.149.0` with R3F, I get these type errors:
```
node_modules/@react-three/fiber/dist/declarations/src/core/hooks.d.ts:12:108 - error TS2344: Type 'InstanceType<L>["loadAsync"]' does not satisfy the constraint '(...args: any) => any'.
12 export declare type LoaderReturnType<T, L extends LoaderProto<T>> = T extends unknown ? Awaited<ReturnType<InstanceType<L>['loadAsync']>> : T;
~~~~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/@react-three/fiber/dist/declarations/src/core/hooks.d.ts:12:108 - error TS2536: Type '"loadAsync"' cannot be used to index type 'InstanceType<L>'.
12 export declare type LoaderReturnType<T, L extends LoaderProto<T>> = T extends unknown ? Awaited<ReturnType<InstanceType<L>['loadAsync']>> : T;
~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
This is caused by …
> fix(types): add loadAsync to Loader interface

- packages/fiber/src/core/utils.ts
According to caniuse.com, support of public class fields is around 92%.
https://caniuse.com/?search=class%20fields
Wondering if it make sense to refactor the usage in here (it's the only occurence I found, might not worth to adapt the build to transpile this)
Let me know.
PS:
I discovered this thx to [es-check](https://github.com/yowainwright/es-check) with es2017 target.   The CI was failing https://github.com/belgattitude/perso/actions/runs/4091656424/jobs/7055889714.
> Refactor ErrorBoundary to not use public class fields

- babel.config.js
- packages/fiber/src/core/utils.ts
> According to caniuse.com, support of public class fields is around 92%, see https://caniuse.com/?search=class%20fields. 
Enable transpilation of public class properties in babel.
See https://babel.dev/docs/en/babel-plugin-proposal-class-properties 
Linked to https://github.com/pmndrs/react-three-fiber/pull/2748
Class properties in the dist
Class properties are transpiled
Seems a very small size increase: `76505` vs `76444` bytes (in the esm build)
<details>
<summary>ls -la ./dist</summary>
```
// with class properties in babel
-rw-rw-r-- 1 sebastien sebastien 78461 févr.  4 14:43 index-455b51ca.cjs.prod.js
-rw-rw-r-- 1 sebastien sebastien 78504 févr.  4 14:43 index-6442a2a3.cjs.dev.js
-rw-rw-r-- 1 sebastien sebastien 76505 févr.  4 14:43 index-7dbf758c.esm.js
-rw-rw-r-- 1 sebastien …
```
> Babel: transpile class properties for wider browser support

- packages/fiber/src/core/utils.ts
- packages/fiber/tests/core/renderer.test.tsx
Skips instance invalidation calling `onUpdate` whenever the scope or reference to `onUpdate` is the only change in a render. This improves stability in lambda components (e.g. `const Component = (props) => <mesh {...props} onUpdate={props.onUpdate} />`).
> fix: skip circular onUpdate calls

- docs/API/events.mdx
For some reason, the space character broke the markdown rendering of titles.
> docs: fix broken titles on events.mdx

- packages/fiber/src/core/utils.ts
Will only try to encode textures as sRGB when they are a valid RGBA8 texture as per https://github.com/mrdoob/three.js/pull/23129.
> fix: don't try to encode invalid sRGB textures

- packages/fiber/src/core/index.tsx
- packages/fiber/src/core/utils.ts
- packages/fiber/tests/core/renderer.test.tsx
Prefers to set `THREE.ColorManagement.enabled` over `THREE.ColorManagement.legacyMode` if able (see https://github.com/mrdoob/three.js/pull/24940). This is a contentious part of THREE's API, so this will let us work around any further mutations without deprecation warnings.
> fix(core): set THREE.ColorManagement.enabled if able

- packages/fiber/src/core/index.tsx
- packages/fiber/src/core/store.ts
Fixes #2765
```tsx
import * as THREE from 'three'
import { extend, createRoot } from '@react-three/fiber'
const canvas = document.createElement('canvas')
document.body.appendChild(canvas)
const offscreen = canvas.transferControlToOffscreen()
extend(THREE)
createRoot(offscreen).render(<gridHelper onBeforeRender={console.log} />)
```
> fix: play nice with OffscreenCanvas

- packages/fiber/src/core/index.tsx
- packages/fiber/tests/core/renderer.test.tsx
> fix: don't overwrite public cameras

- packages/fiber/src/core/index.tsx
- packages/fiber/src/core/renderer.ts
- packages/fiber/src/core/utils.ts
- packages/fiber/tests/core/renderer.test.tsx
Fixes #2794
Removes dynamic expressions around the `THREE` namespace to permit tree-shaking. Since `THREE.ColorManagement` is an optional global in v8 (we implement a fallback), I've opted to access it from the internal catalogue. We'll bump the three peer dep to >=139 in v9 so we can simply do `THREE.ColorManagement` and in accordance with breaking changes in the types.
> fix: treeshake THREE.ColorManagement

- docs/advanced/scaling-performance.mdx
- docs/getting-started/your-first-scene.mdx
- docs/tutorials/typescript.mdx
- docs/tutorials/v8-migration-guide.mdx
* Revised sample code in your-first-scene.mdx to use React 18 createRoot API
* Removed a few typos in multiple docs
> Fix typo in docs

- CONTRIBUTING.md
Since it's the one that's currently used.
> Made yarn link point to classic yarn

- docs/API/canvas.mdx
- docs/tutorials/v8-migration-guide.mdx
- packages/fiber/src/core/index.tsx
- packages/fiber/src/core/store.ts
- packages/fiber/src/core/utils.ts
- packages/fiber/tests/core/renderer.test.tsx
Sets `gl.outputColorSpace` (https://github.com/mrdoob/three.js/pull/25756) and `Texture.colorSpace` (https://github.com/mrdoob/three.js/pull/25771) since r152.
This is one of the last relevant changes aside from switching to sRGB by default, and maybe disabling legacy lighting (see https://github.com/mrdoob/three.js/issues/23614).
> fix: set outputColorSpace with r152

- packages/fiber/src/native/Canvas.tsx
- packages/fiber/src/web/Canvas.tsx
Aliases the `Props` type as `CanvasProps`. This is already renamed on the v9 branch.
> feat(Canvas): alias Props => CanvasProps

- docs/advanced/pitfalls.mdx
- docs/advanced/scaling-performance.mdx
- docs/getting-started/installation.mdx
- docs/getting-started/introduction.mdx
- docs/tutorials/loading-models.mdx
- docs/tutorials/typescript.mdx
There were some problems with the previous useRef naming
It was different every time:
```
const canvasRef = useRef...
const ref = useRef...
const mesh = useRef...
```
Now, every ref is named: `name of the component` + `Ref`
For example: a ref for a mesh would be: `meshRef`; a mesh for a canvas would be: `canvasRef`.
This also improves readability, because:
1. We don't have repeating names:
It would have usually been something like:
```
const mesh = useRef...
...
<mesh
ref={mesh}
...
/>
```
2. We know where each ref belongs to:
Some refs would only have the name `ref`
> docs: common and readable useRef naming

- packages/test-renderer/src/createTestCanvas.ts
Fixes a regression discovered in https://github.com/pmndrs/react-three-fiber/pull/2878#issuecomment-1589257595. Will need to create a more robust canvas shim for RTTR and native it seems.
> fix(RTTR): fallback to canvas shim

- packages/test-renderer/src/createTestCanvas.ts
> fix(RTTR): implement HTMLCanvasElement.getContext

- packages/fiber/src/three-types.ts
Fixes #2926 which broke since the introduction of overloads in https://github.com/three-types/three-ts-types/pull/484.
This will need to be vetted in v9 cc @krispya.
> fix(types): harden colors overload since r153

- docs/advanced/scaling-performance.mdx
- docs/tutorials/basic-animations.mdx
- docs/tutorials/v8-migration-guide.mdx
Find small typos while researching fiber documentation and fix them
> docs: Fix typos

- packages/fiber/src/core/index.tsx
Hardens XR initialization against WebXRManager shims from https://github.com/mrdoob/three.js/pull/26079.
> fix: harden XR init against Renderer shim

- docs/advanced/scaling-performance.mdx
Root state does not have setPixelRatio() but rather setDpr()
> fix: Typo in performance regression docs

- packages/fiber/src/core/reconciler.ts
- packages/fiber/src/three-types.ts
Mirrors #2931 in v9's JSX types.
> [v9] fix: r153 colors overload

- packages/fiber/src/core/hooks.tsx
- packages/fiber/tests/core/hooks.test.tsx
> fix(useLoader): dispose loaders

- packages/fiber/src/native/polyfills.ts
Logic should be consistent with FileLoader
This fixes an issue when loading textures from app private storage, with paths such as `file://path/to/texture`.
If an FBX resides in a local path such as `file://path/to/scene.fbx`. `FBXLoader` parses this path, extracts the path from it: `file://path/to/` and calls `loader.parse` with the resource path.
`TextureLoader` should respect this setting and load the textures from the passed in asset directory.
> fix(native): TextureLoader should remain consistent with FileLoader

- packages/fiber/__mocks__/react-native.ts
- packages/fiber/__mocks__/react-native/Libraries/Blob/BlobManager.js
- packages/fiber/__mocks__/react-native/Libraries/Pressability/Pressability.ts
- packages/fiber/src/native/Canvas.tsx
- packages/fiber/src/native/events.ts
Uses `PanResponder` over `Pressability` internals for events (`Pressable` doesn't implement `onPressMove`). `react-native-web` crudely rewrites `react-native/*` which breaks fs paths or `package#exports`. Consequently, we can't leverage feature flags for W3C pointer events.
> feat(native): use PanResponder for react-native-web

- packages/fiber/src/native/Canvas.tsx
- packages/fiber/src/native/polyfills.ts
Minimizes filesystem work when caching assets and disables MSAA on iOS.
> perf(native): don't double encode assets

- packages/fiber/src/core/hooks.tsx
Aligns `Loader` with https://github.com/three-types/three-ts-types/pull/570.
> fix(useLoader): loosen Loader onError signature

- packages/fiber/src/native/polyfills.ts
Drops use of `expo-file-system#getInfoAsync` which is not implemented on web.
> fix(native): drop fsstat for react-native-web

- packages/fiber/src/native/polyfills.ts
Fixes #3027 since https://github.com/pmndrs/react-three-fiber/commit/2cdd86c7465fdf98102dd35c828a8dc3e957311e of #2982.
> fix(native): amend BlobManager over globals

- packages/fiber/src/native.tsx
- packages/fiber/src/native/polyfills.ts
- packages/fiber/tests/native/hooks.test.tsx
Partial revert of #2982 which is producing undefined promise rejections somewhere in the network stack.
We'll revisit once things improve upstream and look into `useLoader` overloads via `Loader#parse` in the meantime.
> fix(native): revert usage of networking stack

- .prettierrc
- packages/fiber/package.json
- packages/fiber/src/native.tsx
- packages/fiber/src/native/Canvas.tsx
- packages/fiber/src/native/polyfills.ts
- yarn.lock
Fixes #1972
Fixes #3049
#3042 introduced a logical regression for Android APK, but also operated under a false premise that previous anonymous errors came from `Blob`/`FileReader` internals and instead was from `XMLHttpRequest`. Although `FileReader.readAsArrayBuffer` was since implemented in `react-native` (polyfill available for older versions), `fetch` still has issues loading data or local uris. I've mirrored https://github.com/pmndrs/react-three-fiber/issues/3049#issuecomment-1772568665 with `buffer` which implements such and restored enhancements from #2982.
> fix(native): restore polyfill conversions, drop networking

- docs/API/additional-exports.mdx
- packages/fiber/src/core/index.tsx
- packages/fiber/src/core/utils.ts
Resolves #2664
Resolves #3000
Exports `buildGraph` which is used internally by `useLoader` to populate `nodes` and `materials` since three.js upstream doesn't do so for `GLTFLoader`. It's possible we remove this in the future should this become a native feature despite its depart from glTF.
> feat: export buildGraph

- packages/fiber/package.json
- packages/fiber/src/core/index.tsx
- packages/fiber/src/core/loop.ts
- packages/fiber/src/core/store.ts
- packages/fiber/src/core/utils.ts
- packages/fiber/src/three-types.ts
- yarn.lock
Fixes #2501
Fixes #3038
Does feature detection via https://github.com/three-types/three-ts-types/pull/222 to prefer WebXR ambient types and falls back to three vendored types. Also ignores deprecated JSX types.
> fix(types): ignore deprecated JSX, use correct XRFrame definition

- packages/fiber/src/core/index.tsx
- packages/fiber/src/core/store.ts
Fixes #3054 where `updateStyle` caused a mismatch in the state model versus incoming props.
> fix(core): harden size state check

- packages/fiber/src/core/index.tsx
Fixes https://github.com/pmndrs/react-three-fiber/issues/3057 where `LineSegments2` requires camera access.
> fix: configure camera for raycaster

- packages/fiber/src/native/polyfills.ts
Fixes #3058 for `URL.createObjectURL` when `BlobManager` is initialized improperly on Android due to missing permissions.
> fix(native): workaround Android content policy for Blob URI

- packages/fiber/__mocks__/react-native.ts
- packages/fiber/src/native/polyfills.ts
Follow-up to #3059. Unpacks blobs from Android content urls when specified by the native `BlobModule`. When not configured as per https://github.com/pmndrs/react-three-fiber/issues/3058#issuecomment-1774039376, we fallback to a base64 uri since internal parts data is already encoded.
> fix(native): harden Blob URI check for Android

- packages/fiber/src/three-types.ts
- tsconfig.json
Follow-up to #3052. `ts-ignore` comments for possibly deprecated code were stripped due to https://github.com/microsoft/TypeScript/issues/38628 and the use of `removeComments`.
> fix(types): preserve deprecated JSX annotations

- packages/fiber/src/core/renderer.ts
- packages/fiber/tests/core/renderer.test.tsx
- packages/test-renderer/src/__tests__/__snapshots__/RTTR.core.test.tsx.snap
Follow-up to #2679. Tries to implement a stable `object` sort for non-scene-graph children.
> experiment: stable object sort

- packages/fiber/src/core/events.ts
Mirrors the fix from https://github.com/pmndrs/drei/pull/1696 for events.
> fix(types): remove use of Object3D generic

- packages/fiber/src/core/renderer.ts
- packages/test-renderer/src/__tests__/__snapshots__/RTTR.core.test.tsx.snap
Reverts #3066 due to unwanted downstream effects. Investigating in #3068.
> Revert "experiment: stable object sort (#3066)"

- packages/fiber/src/native/polyfills.ts
Fixes #3075. Uses the slow path from #3059 for iOS.
> fix(native): deopt iOS blob URI path

- packages/fiber/src/core/renderer.ts
- packages/fiber/tests/core/renderer.test.tsx
Fixes an issue where primitive children are disposed when their parent is disposable.
> fix: don't recursively dispose primitives

- packages/fiber/src/core/hooks.tsx
The current types import from `three/examples/jsm/loaders/GLTFLoader` which is not a valid import path based on three.js's `package.json` "exports" and therfore produces a type error when using `"moduleResolution": "bundler"`:
```
Error: ./node_modules/@react-three/fiber/dist/declarations/src/core/hooks.d.ts(4,22): error TS2307: Cannot find module 'three/examples/jsm/loaders/GLTFLoader' or its corresponding type declarations.
```
Adding the `.js` extension allows TypeScript to resolve to the correct file.
> fix(types): update import from three/examples

- packages/fiber/src/core/hooks.tsx
- packages/fiber/tests/core/hooks.test.tsx
Fixes cases where different `GLTF` versions from `@types/three` and forks like `three-stdlib` may disagree.
> fix(useLoader): loosen GLTF inference check

- packages/fiber/src/core/utils.ts
Fixes #3110. Mirrors #3062 for `XRFrame`.
> fix(types): preserve deprecated XR type annotations

- packages/test-renderer/src/__tests__/RTTR.hooks.test.tsx
- packages/test-renderer/src/index.tsx
This PR addresses issue #3133. It includes two main changes:
1. **Bug Fix**: Corrects the error in the `viewport` and `camera` objects by explicitly creating the size object in the `configure` function to ensure proper passing of width and height properties.
2. **Test Update**: Enhances the test for the `useThree` hook to accurately reflect and validate the size object's structure, using specific dimensions to improve test reliability.
These changes ensure that the `configure` function correctly handles size properties, and the updated test verifies this functionality effectively.
I began by inspecting the source files for the `fiber` package. I noticed that the [configure function](https://github.com/pmndrs/react-three-fiber/blob/master/packages/fiber/src/core/index.tsx#L182) (returned …
> fix(RTTR): set initial size for NaN in viewport

- packages/fiber/src/native/Canvas.tsx
> fix(native): use MSAA for antialias on iOS

- .github/workflows/test.yml
The CI uses matrix notation for setting Node.js version, but there's no matrix strategy set, so it's getting ignored.
The change sets Node.js version 18 expliticly, and removes unused `matrix.node` calls.
Why 18? Because this is the one that's actually being set by default, if you see the latest run: https://github.com/pmndrs/react-three-fiber/actions/runs/7384710806/job/20088098184
> fix(ci): matrix

- packages/fiber/src/three-types.ts
`THREE.Vector` was [removed in `@types/three@0.161.0`](https://github.com/three-types/three-ts-types/releases/tag/r161) in favor of just using type unions.
> fix(types): remove usage of THREE.Vector

- packages/fiber/src/core/utils.ts
- packages/fiber/src/three-types.ts
- [`THREE.WebGLRenderTargetOptions` was removed in `@types/three@0.162.0`](https://github.com/three-types/three-ts-types/releases/tag/r162). Added a `@ts-ignore` since it's being used for feature/version detection.
- [`Float64BufferAttribute` was removed from three.js in r162](https://github.com/mrdoob/three.js/pull/27807). Added a `@ts-ignore` in accordance with how this is dealt with in the status quo.
> fix(types): support @types/three@0.162.0

- packages/fiber/src/core/loop.ts
Currently frames is passed as a second argument of forEach, which does nothing in the way we use invalidate.
I assume it's a mistake and was intended to be passed as a second parameters of invalidate()
> fix: correctly pass frames in invalidate

- packages/fiber/src/core/index.tsx
- packages/fiber/src/core/loop.ts
- packages/fiber/src/core/store.ts
Fixes https://github.com/pmndrs/react-three-fiber/issues/3190
> fix(types): avoid emitting THREE.XRFrame

- packages/fiber/src/core/renderer.ts
Three r0.162.0 has now support for `childadded` event in Object3D's
https://github.com/mrdoob/three.js/blob/master/src/core/Object3D.js#L345-L349
Example of implementation for get added objects
```ts
import { useEffect, useMemo, useState } from 'react';
import { Layers, Object3D, Object3DEventMap } from 'three';
import { useThree } from '@react-three/fiber';
import useEventCallback from 'use-event-callback';
/**
* Get all objects in the scene,
*
* Inspired in https://github.com/mrdoob/three.js/pull/16934#issuecomment-506793917
*/
export const useSceneObjects = () => {
const [sceneObjects, setSceneObjects] = useState<Object3D[]>([]);
const scene = useThree(({ scene }) => scene);
const addNode = useEventCallback((evt: Object3DEventMap['childadded']) => {
evt.child.traverse((node) => { …
```
> feat: add childadded event dispatch

- packages/fiber/src/core/hooks.tsx
Fixes an issue with loaders who implement `dispose`. https://github.com/pmndrs/react-three-fiber/pull/2984#discussion_r1564074276
> fix(useLoader): don't dispose of memoized loader

- packages/test-renderer/src/__tests__/RTTR.events.test.tsx
The change prevents `console.warn` output log pollution, as well as covers it with test.
Example of log from the [latest run](https://github.com/pmndrs/react-three-fiber/actions/runs/7630812513/job/20787324972) in `master` branch:
```sh
PASS packages/test-renderer/src/__tests__/RTTR.events.test.tsx
● Console
console.warn
Handler for onPointerUp was not found. You must pass event names in camelCase or name of the handler https://github.com/pmndrs/react-three-fiber/blob/master/packages/test-renderer/markdown/rttr.md#create-fireevent
28 |     }
29 |
> 30 |     console.warn(
|             ^
31 |       `Handler for ${eventName} was not found. You must pass event names in camelCase or name of the handler https://github.com/pmndrs/react-three-fiber/blob/master/packages/test-renderer/markdown/rttr …
```
> RTTR: Prevent warn log in test

- packages/fiber/src/core/hooks.tsx
- packages/fiber/tests/hooks.test.tsx
Supports re-use of external loader instances:
```jsx
import { GLTFLoader } from 'three-stdlib'
import { useLoader } from '@react-three/fiber'
const loader = new GLTFLoader()
function Model() {
const gltf = useLoader(loader, '/path/to/model.gltf')
}
```
> [v9] feat(useLoader): support loader instances

- packages/fiber/src/core/reconciler.tsx
- packages/fiber/src/core/utils.tsx
Fixes a regression from #3224 where React will hide but never unhide WIP instances during Suspense in the glTF example. Need to report upstream as we're uniquely sensitive to this behavior, although we work around WIP or Suspenseful instances in a more robust way. For that reason, we can remove these hooks as they are impure and produce an invalid tree.
I added a failing test in f1a296db1c45e19810089fb9c0efaa259287fb1c to demonstrate this behavior. Fails on v9, passes after this PR. This is since React 19.
> [v9] fix(reconciler): don't implement (un)hideInstance methods

- packages/fiber/src/core/index.tsx
- packages/fiber/src/core/utils.ts
- packages/fiber/tests/core/renderer.test.tsx
> fix(Canvas): don't override camera frustum props

- .codesandbox/ci.json
- .github/workflows/test.yml
In Spring 2024 GitHub will run its actions on Node 20 by default, so it's worth to follow up on that here either:
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
CodeSandbox config supports only Node 18 maximum, however: 
https://codesandbox.io/docs/learn/ci#configuration-format
> chore(CI): GitHub Actions - Node 20

- packages/fiber/src/core/index.tsx
Fixes #3253 
- Added a missing dependency on the `inject` function, which caused the effect to update a portal's store with stale data from the initial render
- The store destruction has been moved to a separate hook, so it continues to run only on component unmount
> fix: createPortal effect merging stale data from initial render

- docs/advanced/pitfalls.mdx
- docs/getting-started/introduction.mdx
- packages/fiber/readme.md
- readme.md
Just a small improvement for docs
> docs: put apostrophe for "React's" matches

- babel.config.js
- example/tsconfig.json
- package.json
- tsconfig.json
The new JSX runtime is faster than the legacy runtime using `React.createElement`
> Use new JSX runtime

- example/src/demos/Lines.tsx
- packages/fiber/src/core/renderer.ts
- packages/fiber/src/core/utils.ts
- packages/fiber/src/native/polyfills.ts
- packages/fiber/src/three-types.ts
- packages/fiber/tests/core/renderer.test.tsx
- packages/test-renderer/src/createTestCanvas.ts
Using @ts-expect-error is preferred over @ts-ignore and considered a better practice.
To see why, check out this great article by @mattpocock: **[How to use @ts-expect-error
](https://www.totaltypescript.com/concepts/how-to-use-ts-expect-error#ts-expect-error-or-ts-ignore)**
User-facing `/** @ts-ignore */` pragmas are preserved due to https://github.com/pmndrs/react-three-fiber/pull/3062
> chore(types): suppress errors with @ts-expect-error directive instead of @ts-ignore

- packages/fiber/src/core/utils.ts
- packages/fiber/tests/core/renderer.test.tsx
Fixes an issue reported in Discord where events add/remove in `applyProps` would write to an empty object.
> fix(applyProps): null check indeterminate instances

- packages/fiber/src/core/reconciler.tsx
Adds shell types for React 19 reconciler changes from canary and beta. [react-reconciler#readme](https://github.com/facebook/react/tree/main/packages/react-reconciler#readme) is still incomplete following https://github.com/facebook/react/pull/28750 which complicated our migration https://github.com/facebook/react/pull/28909.
> fix(types): add shell types for react-reconciler changes

- packages/fiber/src/core/reconciler.tsx
- packages/test-renderer/src/__tests__/__snapshots__/RTTR.core.test.tsx.snap
Refactors `switchInstance` so we swap instances in reverse, handling tricky cases where we sort or shuffle elements in an array with shared objects. Previously, we had to employ clever tricks since we could only modify instances front-to-back in `commitUpdate` (the inherent order from React mutation effects). Now, we accumulate instances to be reconstructed in-place, and process them when we hit a tail sibling which is either the last sibling in a view, or the last sibling in a sequence with an update.
> [v9] fix: swap instances in reverse

- docs/API/additional-exports.mdx
- packages/fiber/src/core/index.tsx
Add a `flushSync` R3F API to do the same thing as the `react-dom` `flushSync` API. Which is to synchronously and immediately render by boosting the priority of changes that occur within the passed callback function.
See https://react.dev/reference/react-dom/flushSync.
Because of its potential performance impact `flushSync` is a "last resort" option when one must synchronize R3F rendering with something else, e.g. DOM changes.
> feat: add flushSync API

- .github/workflows/test.yml
- .prettierignore
- .prettierrc
- package.json
- packages/fiber/tests/core/events.test.tsx
- Replaced [[Deprecated] jsxBracketSameLine](https://prettier.io/docs/en/options.html#deprecated-jsx-brackets) option with [bracketSameLine](https://prettier.io/docs/en/options.html#bracket-line)
- Added check for code formatting in CI
> chore: Prettier CI/CD, remove deprecated options

- readme.md
I wanted to share an enhancement idea that could greatly benefit the community. I propose adding a link to a popularity trend page to the @react-three packages.
By including this link, we can provide valuable insights to new users who are exploring the `@react-three` ecosystem. Understanding the popularity trends of these packages can help developers make informed decisions.
If there's any further assistance or contribution I can provide to support this project, please do not hesitate to reach out. Working together, we can propel the `@react-three` packages' popularity and inspire more exciting developments for the 3D web ecosystem.
> docs: usage trend

- example/src/demos/SVGRenderer.tsx
- packages/fiber/package.json
- packages/fiber/src/web/Canvas.tsx
- packages/fiber/src/web/use-measure.ts
- yarn.lock
Fixes #3295
Inlines react-use-measure since it has a required `react-dom` peer dep. Need native support upstream to make this optional.
> fix(native): inline use-measure for react-dom peerdep

- packages/fiber/src/native/Canvas.tsx
Fixes issue related to `@react-three/drei` repository: [#2067](https://github.com/pmndrs/drei/issues/2067).
The problem exists in [`handleTouchMoveDolly` method of `OrbitControls` class in `three-stdlib`](https://github.com/pmndrs/three-stdlib/blob/main/src/controls/OrbitControls.ts#L787). `dollyDelta.y` value is `NaN`, because `dollyStart.y` and `dollyEnd.y` in `dollyEnd.y / dollyStart.y` are 0. It happens because of [`getSecondPointerPosition` function](https://github.com/pmndrs/three-stdlib/blob/main/src/controls/OrbitControls.ts#L1077) which uses `event.pointerId` to identify pointers in arrays. Because `event.pointerId` is missing the method always returns the same pointer position, giving zero in the next calculations. 
Please also look at `removePointer` and `trackPointer` methods …
> fix(native): missing pointerId in pointer events

- packages/fiber/src/three-types.ts
Fixes https://github.com/pmndrs/react-three-fiber/issues/3361 by making the `Node` type fault tolarant: if the three object does not exist (and the type ends up as being `any`), the `Node` type will catch this and reduce the `any` type to `{}`
> fix(types): fix React typings, fault tolerant Node type

- packages/fiber/src/core/renderer.ts
This PR aims to implement the behavior described in https://github.com/pmndrs/react-three-fiber/issues/3302
I did not achieve to test it on a local project (even though I succeeded a few months ago). Do you have some documentation to provide to compile and test on a project?
> fix: make textinstance no-op instead of warn

- packages/fiber/src/web/use-measure.ts
This adds an [orientation handler](https://developer.mozilla.org/en-US/docs/Web/API/ScreenOrientation) to useMeasure so that when the device rotates it correctly adjusts the canvas. 
Right now, when a phone rotates the window resize event never fires so the canvas doesn't know it should change, and as the resize handler sets the css sizes directly on the canvas it causes it to bleed over the edge or if you go from horizontal to vertical causes it to leave a big black area in the viewport.
You can simulate this in chrome by using the developer tools device preview button. Load a mobile device, Load a canvas (typically a full size one) and then change the orientation with the orientation button.
> fix: add orientation handling

- packages/fiber/src/three-types.ts
Currently, the types for all onClick, ... events expose the `initMouseEvent` function. The `Properties` type definition has the goal to remove all functions, but it only removes functions with one parameter. Therefore the `initMouseEvent` is not removed and the type is forwarded to the event, even though no `initMouseEvent` function exists on the actual event object.
This PR fixes that and uses a more modern way of filtering entries in the map using `as` supported from typescript 4.1 (4 years ago). https://www.typescriptlang.org/docs/handbook/2/mapped-types.html#key-remapping-via-as
> fix: ThreeEvent should not include initMouseEvent

- packages/fiber/src/web/use-measure.ts
The previous version supported the latest screenOrientation API: https://developer.mozilla.org/en-US/docs/Web/API/ScreenOrientation
But of course iOS does not support this so was throwing errors.
This adds checks to make sure the objects exists and listeners can be added.
Falls back to depreciated method `orientationchange` on the window: https://developer.mozilla.org/en-US/docs/Web/API/Window/orientationchange_event
If that doesn't exist either we have to pray the resize events correctly fire.
closes #3371
> fix: useMeasure to include safer orientation handling

- docs/tutorials/events-and-interaction.mdx
I don't think it's required for these simple examples.
> Remove reference to `myMesh` ref

- packages/fiber/src/core/index.tsx
- packages/fiber/src/core/renderer.ts
- packages/fiber/src/core/store.ts
- packages/fiber/src/core/utils.ts
Loosens checks using `instanceof` for Codesandbox, which duplicates copies of three.js and breaks constructor identity. Materials/geometry won't automatically attach if they have a different constructor identity and break the `instanceof` check.
The `copy` codepath in `applyProps` and HMR still won't work entirely correctly, and this needs a proper fix on Codesandbox.
> fix: loosen instanceof checks for CSB issue

- packages/fiber/package.json
- packages/test-renderer/package.json
Narrows the peer dep range for React to ^18 as we do not yet support React 19. See #2331.
> fix: narrow React peer dep range

- packages/eslint-plugin/package.json
The publish files don't include type declare files.
> fix(eslint-plugin): include type declare files

- packages/fiber/__mocks__/react-native.ts
- packages/fiber/src/native/Canvas.tsx
- packages/fiber/src/web/Canvas.tsx
https://react.dev/blog/2024/04/25/react-19#ref-as-a-prop
> [v9] chore: replace forwardRef with props.ref

- packages/fiber/src/core/utils.tsx
- packages/fiber/tests/utils.test.ts
Fixes an issue [reported on Discord](https://discord.com/channels/740090768164651008/1326482620522958888) where R3F will attempt to copy props even if they don't have the same constructor.
> [v9] fix: only copy props if same constructor

- packages/fiber/src/core/reconciler.tsx
- packages/fiber/src/core/utils.tsx
- packages/fiber/tests/events.test.tsx
Ensures primitives have their props set after container effects are fired and the subtree is completed.
This aligns behavior with native elements and fixes #3437 where event handlers were not registered on initial mount.
> fix: set primitive props after link

- packages/fiber/package.json
- yarn.lock
Updates use measure to sidestep https://github.com/pmndrs/react-use-measure/issues/106 in some installations.
> fix: update use-measure

- packages/fiber/src/core/events.ts
- packages/fiber/tests/events.test.tsx
Fixes #3437
Bubbles up events and state from children of primitives, which fixes an issue where glTF children are not interactive and events are swallowed (pointermiss is not forwarded).
> [v9] fix(events): bubble up events from primitive children

- docs/API/canvas.mdx
- packages/fiber/src/core/renderer.tsx
- packages/fiber/tests/hooks.test.tsx
- packages/fiber/tests/index.test.tsx
- packages/fiber/tests/renderer.test.tsx
- packages/fiber/tests/utils.test.ts
Partial revert of 76fca8f02be336ffa3d84b1b96075d7cb55aa783. Waits for a configured root to resolve or configures itself when calling `root.render()`.
> [v9] fix: don't require configure before render

- packages/fiber/src/core/reconciler.tsx
- packages/fiber/src/core/utils.tsx
- packages/fiber/src/three-types.ts
- packages/fiber/tests/renderer.test.tsx
The affected tags are "audio", "source", "line" and "path". These get prefixed with "three" automatically so for example "audio" becomes "threeAudio". This disambiguates with DOM types.
> [v9] fix: JSX tag conflicts are prefixed with three

- packages/fiber/src/core/utils.tsx
- packages/fiber/tests/utils.test.ts
Hardens applyProp's copy case where it is only reachable for math classes, which are probably read-only (e.g., `Object3D.position`/`Object3D.rotation`). This means we do not copy most props, even if they have identical signatures, and they are passed by reference.
> [v9] fix(applyProps): harden copy case

- packages/fiber/src/web/events.ts
- packages/fiber/tests/events.test.tsx
Between https://github.com/pmndrs/react-three-fiber/commit/8e3b41ed05fc9160530ea27d59e6567e74bddf01 and https://github.com/pmndrs/react-three-fiber/commit/29ed73ffaf960af4dc231f4a5706dc8c37f3ee05, the default (client) behavior was lost and broken when adding left/right page offsets.
> [v9] fix(events): align default event offset behavior

- packages/fiber/src/core/utils.tsx
- packages/fiber/tests/utils.test.ts
Continues #3457, where modifications to `Number.prototype` that implement a math interface would fallthrough to vector shorthand methods like `set`/`copy` and not mutate props.
> [v9] fix(applyProps): narrow vector shorthand to object types

- packages/fiber/package.json
- yarn.lock
Adds `use-sync-external-store`, which is a peer dependency since Zustand v5.
> fix: add use-sync-external-store dep

- packages/fiber/src/core/reconciler.tsx
- packages/fiber/tests/renderer.test.tsx
Fixes #3469, where resolution for JSX conflicts in #3451 erroneously removed `three*` from user-land elements.
> fix(reconciler): prefer to resolve unprefixed instance types

- packages/fiber/src/three-types.ts
Removes the recursive references added to JSX types in #3451.
> fix(types): remove recursive references in JSX types

- packages/fiber/src/three-types.ts
Follow-up to #3472, where conflicting keys need to be removed when using React runtime types.
> fix(types): exclude type conflicts in React runtime types

- example/src/demos/Gltf.tsx
- example/src/demos/MultiView.tsx
- example/src/demos/Portals.tsx
- example/src/demos/StopPropagation.tsx
- example/src/demos/ViewTracking.tsx
- packages/fiber/src/core/utils.tsx
- packages/fiber/tests/hooks.test.tsx
Adds a typed meshes prop to the `ObjecgtMap` created by the loader graph. This allows for using meshes from `useLoader` or `useGltf` without needing to explicitly type the entire graph.
> feat: add meshes to loader graph

- packages/fiber/src/core/reconciler.tsx
- packages/fiber/tests/renderer.test.tsx
This fixes a bug where keyed components changing order would duplicate themselves in the children array instead of repositioning.
> fix(reconciler): out of order children move to the correct position during rerenders

- .github/workflows/test.yml
Adds rsbuild to the CI tests since it does more strict checks than Vite and catches missing import errors, for example.
> chore: add rsbuild to CI test

- .changeset/thick-rice-switch.md
- packages/fiber/src/core/utils.tsx
Removed here: https://github.com/facebook/react/pull/32200
Released in react@19.1.0, [changelog](https://github.com/facebook/react/blob/main/CHANGELOG.md#1910-march-28-2025).
Raised in Discord: https://discord.com/channels/740090768164651008/740093168770613279/1355564374319829235
> Fix builds failing from React.act being removed from the production bundle

- packages/fiber/src/core/utils.tsx
Fixes #3511 thanks to @eps1lon.
> https://github.com/pmndrs/react-three-fiber/pull/3508/ won't be sufficient for certain bundlers like Webpack. They treat namespace access like a named import (https://github.com/webpack/webpack/issues/14814) so you need to trick those bundlers e.g. `React['act' + '']`
`act` is deprecated since v9 and will be removed from react-three-fiber in the next major and should be imported from React instead https://r3f.docs.pmnd.rs/tutorials/v9-migration-guide#act.
> fix: reference dev-only act with computed key for Webpack

- jest.config.js
- packages/test-renderer/markdown/rttr.md
- packages/test-renderer/src/__tests__/RTTR.core.test.tsx
- packages/test-renderer/src/__tests__/__snapshots__/RTTR.core.test.tsx.snap
- packages/test-renderer/src/createTestInstance.ts
- packages/test-renderer/src/helpers/graph.ts
- packages/test-renderer/src/helpers/testInstance.ts
This PR addresses two significant issues in the React Three Test Renderer:
1. **Primitive Children Not Visible**: Previously, when using `<primitive object={object} />` components, the children of these objects were not visible in the test renderer's output. This made it impossible to test or traverse the full scene graph when primitives were used.
2. **Incorrect Query Behavior**: The search methods (`findByType`, etc.) were including the current node in search results, which made it difficult to search for nested elements of the same type.
- Modified `createTestInstance.ts` to detect primitive components and include their THREE.js children in the virtual tree
- Added a recursive `createVirtualInstance` helper that creates instance representations for THREE.js objects
- Updated `graph.ts` …
> Handle primitives in test-renderer and fix queries in TestInstances

- packages/fiber/src/core/index.tsx
- packages/fiber/tests/__snapshots__/canvas.native.test.tsx.snap
- packages/fiber/tests/__snapshots__/index.test.tsx.snap
The export got removed from v9, presumably by accident. This adds it back.
> chore: export flushSync

- packages/fiber/src/native/polyfills.ts
In the incoming React Native 0.79 release, we've converted a number of internal modules to `export` syntax — affecting usages with `require()`. This PR attempts to update these imports ahead of time, to work with both versions.
💡 Secondary note: In a future release, we are intending to omit each of these deep-imported modules from the public API of React Native. There will be a consultation period on opening up new APIs via the root `'react-native'` exports — e.g. `BlobManager` here.
**Needs testing**. CI should pass for integration with current RN versions.
> Update react-native deep imports for 0.79 compatibility
