- index.js
- `arrow function`
- `destructuring binding`
- `var` => `let`
> Refactor: ES6

- .size-snapshot.json
- package.json
- src/reconciler.js
@drcmda i normally prefer standard js :)
let me know if you'd prefer to create a utility file and import the functions for readability!
> removed lodash dependency for es6 implementation

- package.json
Three.js semver is stuck on minor releases, the latest is 0.102.1 for instance
> Tweak three peer dep version

- index.js
`useResource` is in the documentation but is not exported from the latest version.
> Add export for useResource

- src/reconciler.tsx
> Add detection for changes in argument objects

- readme.md
`color` props has not been used in functional component.
> Fix: update sample code

- readme.md
Removing extra closing parenthesis on useLoader
> docs: Updating README

- readme.md
Great work on the new version, looks amazing.
> Fixed broken recipes link

- examples/components/Swarm.js
> Fix swarm example imports

- readme.md
I know this is small, but it took me a few minutes to debug why the `pixelRation` prop wasn't working for me. Hope this helps someone!
> Fix prop typo

- migration.md
- readme.md
> Fix documentation regarding removed hook variable

- .gitignore
I believe that file should be ignored :D
> Add .size-snapshot.json to .gitignore

- package.json
Merge conflict probably ¯\\_(ツ)_/¯
> Change package.json test script

- src/canvas.tsx
- src/targets/shared/web/ResizeContainer.tsx
- src/targets/web.tsx
This is my initial attempt to tackle issue #282.
Tested on examples project with react-three-fiber 4.0.9 and latest react devtools 4.4.0-f749045a5.
This resolved issues point 1). About point 2) I'm going to continue in the issue comments.
> improve appearance in React Devtools

- whatsnew.md
Trivial change for those copy-pasting this snippet.
> Minor import fix for whatsnew.md

- src/three-types.ts
Fixing types as mentioned in https://github.com/react-spring/react-three-fiber/issues/11#issuecomment-591968815
> Type fixes

- src/reconciler.test.tsx
- src/reconciler.tsx
> idempotent sibling nodes movement

- examples/src/demos/dev/Viewcube.js
I just found that, scene is not loaded from useThree in Viewcube component.
> found a missing word

- src/three-types.ts
> Add fog type

- readme.md
- src/targets/shared/web/Dom.tsx
Hi,
I have been experimenting with this great project and have decided to test it on a project that I am working on. I made the following improvements (improvements in my opinion :-)) to the `Dom` component:
**1. Do not render Dom elements if 3D object is behind the camera**
Currently, elements that are behind the camera are still projected onto the screen and rendered. I think, this is unwanted in most cases. The problem is shown in this gif:
This pull request will hide Dom elements which are behind the camera.
**2. Added `scaleFactor` property to Dom**
I added a new property to Dom: scaleFactor. If scaleFactor is undefined, the Dom component behaves unchanged from the current implementation. If scaleFactor is a number, the element will scale according to the distance from the camera and …
> Improvements to the Dom component

- examples/src/demos/index.js
Sorry in the confusion of that formatting issue I accidentally removed a 'd' on the var name which broke the branch, I have added it back.
> Fixing broken variable name

- examples/config-overrides.js
> Remove refresh warning

- examples/src/demos/dev/Bloom.js
> Fix Bloom.js warnings

- examples/src/demos/dev/Reparenting.js
> Fix Reparenting.js warnings

- examples/src/demos/dev/GltfAnimation.js
> Fix GltfAnimations.js warnings

- examples/src/demos/dev/Dom.js
> Fix Dom.js warnings

- examples/src/demos/dev/Suspense.js
> Fix Suspense.js warnings

- examples/src/demos/VolumetricLight.js
> Fix VolumetricLight.js warnings

- examples/src/demos/dev/MultiScene.js
> Fix MultiScene.js warnings

- examples/src/demos/dev/Viewcube.js
- package.json
- yarn.lock
> Fix Viewcube.js warnings

- examples/src/demos/Montage.js
> Fix Montage.js warnings

- examples/src/demos/dev/Hud.js
> Fix Hud.js warnings

- examples/src/demos/dev/WebGL2.js
> Fix WebGL2.js warnings

- examples/src/demos/GltfPlanet.js
> Fix GltfPlanet.js warnings

- examples/src/demos/Font.js
> Fix Font.js warnings

- examples/src/resources/postprocessing/WaterPass.js
> Fix WaterPass.js warnings

- examples/src/demos/dev/Concurrent.js
> Fix Concurrent.js warnings

- examples/src/demos/dev/Scroll.js
> Fix Scroll.js warnings

- examples/src/demos/SVGLoader.js
> Fix SVGLoader.js warnings

- examples/src/demos/dev/Selection.js
> Fix Selection.js warnings

- examples/src/demos/dev/ShaderMaterial.js
> Fix ShaderMaterial.js warnings

- recipes.md
- Use new bootstrapping option
- Added notice about emulators
- Added info about Expo web support
- Related https://github.com/expo/examples/pull/176
> [docs] Updated expo/native section

- examples/src/demos/dev/Lines.js
> Fix Lines.js warnings

- api.md
- pitfalls.md
- recipes.md
Hey, sorry it looks like a commit I did for `recipes.md` TOC the other day was not working when pushed to GitHub (it worked fine in the VScode markdown preview). I also unified style across all 3 files.
> Fix *.md file and unify toc style

- src/three-types.ts
Add missing definition for <instancedBufferAttribute>.
> Add missing TypeScript definition for <instancedBufferAttribute>.

- examples/package.json
- examples/yarn.lock
Small PR here to install `drei` for the [`examples`](https://github.com/react-spring/react-three-fiber/tree/master/examples) app. It's currently not included as a dependency in `./examples/package.json` so the example app setup fails.
Loving this project :v:
> Add missing dependency

- src/reconciler.tsx
Reopening from (https://github.com/react-spring/react-three-fiber/pull/585)
I noticed a few areas for quick performance wins in the reconciler. I'll add comments to each individual section.
One of the [goals for v5](https://github.com/react-spring/react-three-fiber/issues/420) was:
> Rewrite reconciler, make it type-safe, optimize hot paths
In relation to this goal, it would be great to create benchmark tests for each overarching "feature/component" of the library. Examples might be:
- applyProps
- hooks (useFrame, useThree, etc)
- reconciler
I'm envisioning almost like a rollup snapshot printout that is committed -- but instead it would be timings per feature rather than size per artifact. This would enable contributors to compare before/after changes in a standardized and historical …
> small reconciler performance wins

- src/canvas.tsx
Adding the `gl` dependency solves #611
> Add missing 'gl' dependency in useMemo()

- src/canvas.tsx
This PR fixes mouse events order.
In case when cursor is moving from object A to object B:
before:
B.pointerMove
B.pointerOver
A.pointerOut
after:
A.pointerOut
B.pointerOver
B.pointerMove
Issue: https://github.com/pmndrs/react-three-fiber/issues/664
> Fix order of mouse events

- api.md
These doesn't seems to be in the code anymore?
> docs: remove onPointerEnter and onPointerLeave

- api.md
> Add more details on event propagation to api.md

- src/renderer.tsx
here I've fixed Reconciler import, and also couple more issues. Ready to merge.
> fix reconsciler issue, fix couple ts issues

- markdown/pitfalls.md
fix missed conflicts in pitfalls.md
> fix(docs): resolve conflicts

- src/components/types.ts
> Fix exporting omitByValue

- src/canvas.tsx
> changes internal Camera type to THREE.Camera

- src/renderer.tsx
> fix: Typo in extraneous text error

- examples/src/demos/dev/Lines.js
- Replace geometry with bufferGeometry
Fixes https://github.com/pmndrs/react-three-fiber/issues/1009
> Updates Lines example after Three.geometry deprecation

- packages/fiber/src/core/loop.ts
- packages/fiber/src/core/store.ts
Use precise `setTimeout`  return type
> chore: enhance type

- example/src/App.tsx
- packages/fiber/src/core/renderer.ts
create instances on the fly for defaults then throw them out. 
relates to #981
> [v6] prop-defaults

- packages/fiber/src/web/index.tsx
- packages/fiber/tests/web/canvas.test.tsx
This is related to https://github.com/pmndrs/react-three-fiber/issues/1159
> Attempt to fix VR prop

- packages/fiber/src/web/Canvas.tsx
> Fixed type import in `Canvas.tsx`

- packages/fiber/src/core/store.ts
When investigating https://github.com/pmndrs/react-three-fiber/issues/1177 I found the problem to be due to subscribers not being unsubscribed properly, it's not even related to `vr={true}`.
**How to see the issue in action**
1. Open the sandbox, e.g. https://codesandbox.io/s/r3f-basic-demo-forked-ics6o?file=/src/App.js
2. Change the `intensity` prop of `ambientLight` to something else
3. Observe the boxes rotate faster after a hot reload
This PR should fix the issue.
It would be nice to have a test for this maybe, what do you think?
> Fixed `useFrame` subscribers to unsubscribe properly

- packages/fiber/src/three-types.ts
Addresses issue discussed in https://github.com/pmndrs/react-three-fiber/issues/1200.
> fix layers typing regarding set argument

- packages/fiber/src/core/renderer.ts
- packages/fiber/tests/web/web.core.test.tsx
There are cases where you might want to attach an Object3D child to a property of a parent, just like you can with non-Object3D instances today. For example, you might have a render pass (managed in EffectComposer) with a `scene` member, and you want to have its scene in the R3F tree.
This change flips the order that the isObject3D check and the child.attach* checks run in appendChild and insertBefore, so that an Object3D child that has one of the attach props will get attached instead of being a scene-graph child, regardless of whether the parent is an Object3D. It also updates removeChild to match.
The test suite gets a new test for this behaviour.
> allow attach prop on Object3D

- example/src/App.tsx
- example/src/demos/Animation.tsx
- example/src/demos/Layers.tsx
- example/src/demos/ResetProps.tsx
- packages/fiber/src/core/renderer.ts
- packages/fiber/src/web/index.tsx
IDE was nitting about certain things. So here is some improvements to the code.
> Little improvements

- .codesandbox/ci.json
> ci: fixes codesandbox CI by setting node version in ci.json

- packages/fiber/src/core/store.ts
> fix(core): `flat` should be controlled independently of `linear`

- packages/fiber/src/core/is.ts
- packages/fiber/src/core/store.ts
- packages/fiber/src/web/Canvas.tsx
- packages/fiber/src/web/index.tsx
Fixes #1662 by applying the fix made in #1703 to v7 so we can ship a patch before v8.
> fix(core): fix dpr & size check on render

- packages/fiber/src/native/Canvas.tsx
Fixes #1868 by umounting the current context.
> [v8] fix(Canvas): unmount context

- packages/fiber/src/core/renderer.ts
Fixes #1551 where suspense will create a race condition that can unset attach properties.
> fix(core): fix attach with suspense

- packages/fiber/src/core/events.ts
- packages/fiber/src/core/store.ts
Required to map mouse position from full screen coords to Window coords in `@react-three/scissor`
> Added custom size variables to raycaster

- docs/getting-started/introduction.mdx
Fixed a sentence that had strange grammar / spelling
> Quick documentation grammar fix

- package.json
- packages/fiber/package.json
Recreating of https://github.com/pmndrs/react-three-fiber/pull/2123 for v8.
> Move @types/react-reconciler to dependencies

- docs/tutorials/how-it-works.mdx
Hello,
I noticed two broken paragraphs while reading the documentation, and this PR aims at fixing them.
I hope it helps !
> docs: fix broken paragraphs

- packages/fiber/src/core/hooks.tsx
- packages/fiber/src/native/Canvas.tsx
- packages/fiber/src/web/Canvas.tsx
- close #2110
Memoize function
> fix(event): memoize `onPointerMissed`

- packages/fiber/src/core/hooks.ts
- packages/fiber/src/web/Canvas.tsx
> fix(Canvas): backport onPointerMissed fix

- packages/fiber/package.json
- packages/fiber/src/core/index.tsx
- yarn.lock
> chore: update `@types/react-reconciler`

- packages/fiber/src/core/store.ts
Reverts #1178 where race conditions previously appeared due to stale subscribers on cleanup.
> fix(useFrame): mutate subscribers instead

- packages/fiber/src/core/index.tsx
- packages/fiber/src/core/store.ts
- packages/fiber/tests/core/hooks.test.tsx
- packages/test-renderer/src/__tests__/RTTR.hooks.test.tsx
`updateStyle` should be `false` when threejs is used with offscreen canvas.
> feat: add size options for updateStyle

- packages/fiber/src/index.tsx
Export `createEvents` for custom canvas (offscreen canvas).
> feat: export create-events

- packages/fiber/src/core/store.ts
> [v9] fix: don't updateStyle on offscreen canvas

- docs/API/objects.mdx
> chore(docs): update objects.mdx

- packages/fiber/src/three-types.ts
- packages/fiber/tests/__snapshots__/index.test.tsx.snap
Export the Overwrite type utility for use in Drei.
> [v9] feat: export Overwrite

- packages/test-renderer/src/__tests__/RTTR.core.test.tsx
- packages/test-renderer/src/__tests__/__snapshots__/RTTR.core.test.tsx.snap
- packages/test-renderer/src/index.tsx
Fixes https://github.com/pmndrs/react-three-fiber/issues/2200
> fix(RTTR): backport traverse, update fixes

- .prettierrc
You know the drill. Helps cross platform dev.
> [v9] endOfLine auto

- packages/fiber/src/native/Canvas.tsx
- packages/fiber/src/web/Canvas.tsx
> fix(types): update canvas root types

- packages/fiber/src/web/Canvas.tsx
Prefers to inline render-effects.
> fix(Canvas): inline render-effect

- docs/getting-started/installation.mdx
Since Vite became more popular, I thought it would be nice to introduce newcomers to using Vite with React Three Fiber.
> chore(docs): Added Vite to installation guide

- docs/tutorials/typescript.mdx
> docs: Update typescript.mdx

- .changeset/gorgeous-timers-train.md
This pull request:
- adds a changeset to release the eslint plugin during the next release
More rules will come over time when I (or anyone else 😄) get to them. Let me know if anything stands out.
> Initial release of the ESLint plugin

- packages/fiber/src/core/renderer.ts
- packages/fiber/src/core/utils.ts
> fix: safely diff instances

- packages/fiber/src/native/Canvas.tsx
- packages/fiber/src/web/Canvas.tsx
> fix(Canvas): pass scene prop

- packages/fiber/src/native/polyfills.ts
> fix(native): prefer local uri for fs

- packages/fiber/src/core/utils.ts
Resolves #2856. Partial revert of #2757.
> fix(applyProps): loosen copy identity in dev

- .github/workflows/test.yml
Upgrading the workflows to latest:
- https://github.com/actions/checkout/
- https://github.com/actions/setup-node/
> chore(CI): checkout v4, setup-node v3

- packages/fiber/src/three-types.ts
> [v9] fix: add missing math types

- readme.md
Same as https://github.com/pmndrs/react-three-fiber/pull/3134 but for the readme
> docs: update readme for three.js r155+

- .codesandbox/ci.json
Fixes issue from https://github.com/pmndrs/react-three-fiber/pull/3144
> CodeSandbox: Node 18

- packages/fiber/src/core/loop.ts
Related issue
https://github.com/pmndrs/react-three-fiber/issues/3186
> fix: prevent invalidate from piling up frames

- packages/fiber/tests/renderer.test.tsx
Related: #2679. Tests #3068 against the v9 implementation.
> [v9] chore(tests): add array attach case

- packages/fiber/src/core/utils.ts
PR follow issue https://github.com/pmndrs/react-three-fiber/issues/3277
> fix: update is.equ to compare booleans

- docs/advanced/scaling-performance.mdx
update line 26 [dpr, set]  to [dpr, setDpr]
> docs: typo in scaling-performance.mdx

- docs/getting-started/your-first-scene.mdx
- Canvas closing tag was missing from the code example on one of the tutorials
> docs: Fixed code example in "Your first scene"

- docs/API/canvas.mdx
- docs/API/events.mdx
- docs/API/hooks.mdx
- docs/API/objects.mdx
- docs/advanced/scaling-performance.mdx
- docs/getting-started/installation.mdx
- docs/getting-started/your-first-scene.mdx
- docs/tutorials/how-it-works.mdx
https://docs.pmnd.rs/getting-started/authoring#gha
> docs - deprecated Hint

- packages/fiber/src/native/Canvas.tsx
> fix(native): don't bind events to GLView

- packages/fiber/src/core/loop.ts
Fixes #3436 since d7a5b31af3574a664b99e51e476a0707ab990904.
> fix(loop): cleanup WIP state

- docs/getting-started/community-r3f-components.mdx
- packages/fiber/src/core/utils.tsx
`resolve` does a set check on the target. This adds all the same narrowing done to the other set cehcks in `applyProps` there.
> fix(applyProps): set check when resolving pierced properties

- docs/getting-started/introduction.mdx
- example/src/demos/Portals.tsx
- packages/fiber/CHANGELOG.md
- packages/fiber/package.json
- packages/fiber/src/core/renderer.tsx
- packages/fiber/tests/events.test.tsx
- packages/test-renderer/CHANGELOG.md
- packages/test-renderer/markdown/rttr.md
- readme.md
> chore: fix typos
